version: "3.9"
services:
  discord_sticky-bot:
    image: ethorbit/discord_sticky-message-bot:latest
    container_name: discord_sticky-bot 
    environment:
      STICKY_COOLDOWN: 600000
      BOT_TOKEN: ${DISCORD_STICKY_BOT_TOKEN}
    cpu_shares: 256 
    cpu_percent: 20
    deploy:
      resources:
        limits:
          memory: 50M  
        reservations:
          memory: 20M
    restart: unless-stopped

