version: "3.9"
services:
  unionfs:
    image: ethorbit/unionfs:latest
    container_name: nzc-unionfs-${SERVER_NUMBER}
    user: ${GMOD_UID}:${SFTP_GID}
    privileged: true    
    network_mode: none    
    environment:    
      TZ: ${TZ}    
      PUID: ${GMOD_UID}    
      PGID: ${SFTP_GID}
    volumes:    
      - ${DATA_DIR}/files/${SERVER_NUMBER}:/top:shared    
      - ${DATA_DIR}/files/shared:/bottom:shared    
      - ${DATA_DIR}/srcds/${SERVER_NUMBER}:/merged:shared    
    cpuset: ${CPU}   
    deploy:
      resources:
        limits:
          memory: 50M 
    blkio_config:
      weight: 500
      device_write_bps:
        - path: ${DISK}
          rate: 60000000
      device_read_bps:
        - path: ${DISK}
          rate: 60000000
      device_read_iops:
        - path: ${DISK}
          rate: 120
      device_write_iops:
        - path: ${DISK}
          rate: 50
    restart: always 
  gmod:
    image: ethorbit/srcds-server 
    container_name: nzc-gmod-${SERVER_NUMBER}
    environment:
      SRCDS_APPID: 4020 
      SRCDS_RUN_ARGS: "-tickrate 33 -disableluarefresh +maxplayers 12 +gamemode nzombies +map nz_kino_der_toten"
      USER_ID: ${GMOD_UID} 
      GROUP_ID: ${GMOD_GID}
    ports:
      - ${GMOD_PORT}
    volumes:
      - ${DATA_DIR}/srcds/${SERVER_NUMBER}/files:/home/srcds/server 
    cpuset: ${CPU}
    cpu_shares: 1024 
    deploy:
      resources:
        limits:
          memory: 512M 
        reservations:
          memory: 256M  
    depends_on: 
      unionfs:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "findmnt ${GMOD_DIR}/srcds/${SERVER_NUMBER} | grep unionfs"]
      interval: 1s
      start_period: 2s
      retries: 180
    restart: unless-stopped 
    networks: 
      - gmod
networks:
  gmod:
    name: gmod-${SERVER_NUMBER}
