version: "3.9"
services:
  svencoop:
    image: ethorbit/svencoop-server:latest
    tty: true 
    stdin_open: true
    environment:
      SRCDS_RUN_ARGS: "-port ${SVENCOOP_PORT} +maxplayers 12 +map uplink"
      USER_ID: ${SVENCOOP_UID} 
      GROUP_ID: ${SVENCOOP_GID}
    volumes:
      - svencoop:/home/srcds/server
    ports:
      - ${SVENCOOP_PORT}:${SVENCOOP_PORT}/udp
    networks:
      - svencoop
    cpuset: ${SVENCOOP_CPU}   
    cpu_shares: 512
    deploy:
      resources:
        limits:
          memory: 512M 
        reservations:
          memory: 128M  
    blkio_config:
      weight: 150
      device_write_bps:
        - path: ${DISK}
          rate: 10000000
      device_read_bps:
        - path: ${DISK}
          rate: 20000000
      device_read_iops:
        - path: ${DISK}
          rate: 120
      device_write_iops:
        - path: ${DISK}
          rate: 100
    restart: unless-stopped 
volumes:
  svencoop:
networks: 
  svencoop:
    driver: "bridge"
