version: "3.9"

x-ark: &ark
  build:
    context: ./build/ark-server
    args:
      PUID: ${steam_u}
      PGID: ${ark_g}
      UMASK: "007"
  tty: true
  stdin_open: true
  extra_hosts:
    - "${DOMAIN_NAME}:172.10.1.2"
    - "${WEBSITE_SUBDOMAIN}.${DOMAIN_NAME}:172.10.1.2"
    - "${FASTDL_SUBDOMAIN}.${DOMAIN_NAME}:172.10.1.2"
  labels:
    - "io.portainer.accesscontrol.teams=ark"
  cpu_count: 1
  cpu_shares: 256
  deploy:
    resources:
      limits:
        memory: ${ARK_RAM:-1024M}
      reservations:
        memory: 128M  
  blkio_config:
    weight: 20
    device_write_bps:
      - path: ${DISK}
        rate: '60m'
    device_read_bps:
      - path: ${DISK}
        rate: '60m'
    device_read_iops:
      - path: ${DISK}
        rate: 1000
    device_write_iops:
      - path: ${DISK}
        rate: 1000
  restart: always
x-ark-depends: &ark_depends
  ark_permissions:
    condition: service_completed_successfully
  rsyslog:
    condition: service_healthy
x-ark-development-depends: &ark_development_depends
  nginx_development:
    condition: service_healthy
x-ark-production-depends: &ark_production_depends
  nginx_production:
    condition: service_healthy
      
x-ark-1: &ark_1
  <<: [ *ark ]
  hostname: ark_1
  environment:
    PORT: ${ARK_1_PORT}
    QUERY_PORT: ${ARK_1_QUERY_PORT}
    START_ARGS: "TheIsland?listen?Port=${ARK_1_PORT:-7777}?QueryPort=${ARK_1_QUERY_PORT:-27415}?ServerCrosshair=True?MapPlayerLocation=True?AllowThirdPersonPlayer=True"
    RCON_PASSWORD: ${ARK_PASSWORD}
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./data/configs/users/passwd:/etc/passwd:ro
    - ./data/configs/users/group:/etc/group:ro
    - ./data/configs/users/shadow:/etc/shadow:ro
    - ./data/configs/users/gshadow:/etc/gshadow:ro
    - ${MOUNT_PROC_CPUINFO}:/proc/cpuinfo:rw
    - ${MOUNT_PROC_MEMINFO}:/proc/meminfo:rw
    - ${MOUNT_PROC_SWAPS}:/proc/swaps:rw
    - ${MOUNT_PROC_STAT}:/proc/stat:rw
    - ${MOUNT_PROC_DISKSTATS}:/proc/diskstats:rw
    - ${MOUNT_PROC_UPTIME}:/proc/uptime:rw
    - ${MOUNT_PROC_SLABINFO}:/proc/slabinfo:rw
    - ${MOUNT_SYS_DEVICES_SYSTEM_CPU}:/sys/devices/system/cpu:rw
    - ark_1:${MOUNT_GUEST_STEAMCMD_GAMES}:slave
    - ark_shared:/shared:slave
  ports:
    - ${ARK_1_QUERY_PORT:-27415}:${ARK_1_QUERY_PORT:-27415}/udp
    - ${ARK_1_QUERY_PORT:-27415}:${ARK_1_QUERY_PORT:-27415}/tcp
    - ${ARK_1_PORT:-7777}:${ARK_1_PORT:-7777}/udp
    - ${ARK_1_PORT:-7777}:${ARK_1_PORT:-7777}/tcp
  cpuset: ${ARK_1_CPU}
  networks:
    ark:
      ipv4_address: 172.154.1.1
    nginx:
    mysql:
  logging:
    driver: syslog
    options:
      mode: non-blocking
      syslog-address: "tcp://localhost:${RSYSLOG_PORT}"
      tag: "ark_1"

services:
  ark_permissions:
    build:
      context: ./build/permissions
    volumes:
      - ark_1:/mnt/1
      - ark_shared:/mnt/shared
    command: >
      /bin/sh -c 'for d in shared 1; do 
      chown "${steam_u}":"${ark_g}" "/mnt/$$d" 
      && chmod 2770 "/mnt/$$d" 
      && setfacl -d -m u::rwx,g::rwx,o::- "/mnt/$$d"; 
      done'
    cap_drop:
      - ALL 
    cap_add:
      - CAP_DAC_OVERRIDE
      - CAP_CHOWN
      - CAP_FOWNER
      - CAP_FSETID
    network_mode: none
    restart: on-failure
  ark_1_production:
    profiles:
      - production
    <<: [ *ark_1 ]
    depends_on:
      <<: [ *ark_depends, *ark_production_depends ]
  ark_1_development:
    profiles:
      - development
    <<: [ *ark_1 ]
    depends_on:
      <<: [ *ark_depends, *ark_development_depends ]

volumes:
  ark_1:
  ark_shared:
networks: 
  ark:
    ipam:
      driver: default 
      config:
        - subnet: 172.154.1.0/22
