version: "3.9"
services:
  autoheal:
    image: willfarrell/autoheal:latest
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    restart: always
    network_mode: none

