version: "3.9"
services:
  mysql:
    image: mysql:8.0.32-debian
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=${MYSQL_REMOTE_PASSWORD}
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    networks:
      - mysql
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - mysql:/var/lib/mysql
    restart: always
volumes:
  mysql:
networks:
  mysql:
