version: "3.9"
services:
  discord_sticky-bot:
    image: ethorbit/discord_sticky-message-bot:latest
    environment:
      STICKY_COOLDOWN: 600000
      BOT_TOKEN: ${DISCORD_STICKY_BOT_TOKEN}
    volumes:
      - discord_sticky_bot:/botdb
    cpu_shares: 256 
    cpu_percent: 20
    deploy:
      resources:
        limits:
          memory: 50M  
        reservations:
          memory: 20M 
    blkio_config:
      weight: 50
      device_write_bps:
        - path: ${DISK}
          rate: 10000000
      device_read_bps:
        - path: ${DISK}
          rate: 20000000
      device_read_iops:
        - path: ${DISK}
          rate: 120
      device_write_iops:
        - path: ${DISK}
          rate: 100
    restart: unless-stopped
    networks:
      - discord 
networks:    
  discord:
    name: discord-bots
volumes:
  discord_sticky_bot: 
