version: "3.9"
services:
  discord_permissions:
    build:
      context: ./build/permissions
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - discord_sticky_bot:/mnt/discord_sticky_bot
    command: >
      /bin/sh -c 'chown -R ${stickybot_u}:${discord_g} /mnt/discord_sticky_bot/
      && chmod 2770 -R /mnt/discord_sticky_bot/
      && setfacl -d -m u::rwx,g::rwx,o::- "/mnt/discord_sticky_bot"'
    cap_drop:
      - ALL 
    cap_add:
      - CAP_DAC_OVERRIDE
      - CAP_CHOWN
      - CAP_FOWNER
      - CAP_FSETID
    network_mode: none
    restart: on-failure
  discord_sticky-bot:
    build:
      context: ./build/discord_sticky-message-bot
      args:
        PUID: ${stickybot_u}
        PGID: ${discord_g}
    environment:
      - STICKY_COOLDOWN=600000
      - BOT_TOKEN=${DISCORD_STICKY_BOT_TOKEN}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${MOUNT_PROC_CPUINFO}:/proc/cpuinfo:rw
      - ${MOUNT_PROC_MEMINFO}:/proc/meminfo:rw
      - ${MOUNT_PROC_SWAPS}:/proc/swaps:rw
      - ${MOUNT_PROC_STAT}:/proc/stat:rw
      - ${MOUNT_PROC_DISKSTATS}:/proc/diskstats:rw
      - ${MOUNT_PROC_UPTIME}:/proc/uptime:rw
      - ${MOUNT_PROC_SLABINFO}:/proc/slabinfo:rw
      - ${MOUNT_SYS_DEVICES_SYSTEM_CPU}:/sys/devices/system/cpu:rw
      - ./data/configs/users/passwd:/etc/passwd:ro
      - ./data/configs/users/group:/etc/group:ro
      - ./data/configs/users/shadow:/etc/shadow:ro
      - ./data/configs/users/gshadow:/etc/gshadow:ro
      - discord_sticky_bot:/botdb
    cpu_shares: 256
    #cpu_percent: 10
    deploy:
      resources:
        limits:
          memory: 90M
        reservations:
          memory: 30M
    blkio_config:
      weight: 50
      device_write_bps:
        - path: ${DISK}
          rate: '10m'
      device_read_bps:
        - path: ${DISK}
          rate: '20m'
      device_read_iops:
        - path: ${DISK}
          rate: 120
      device_write_iops:
        - path: ${DISK}
          rate: 100
    depends_on:
      discord_permissions:
        condition: service_completed_successfully
      rsyslog:
        condition: service_healthy
    logging:
      driver: syslog
      options:
        mode: non-blocking
        syslog-address: "tcp://localhost:${RSYSLOG_PORT}"
        tag: "discord_sticky_bot"
    restart: always
    networks:
      - discord 
networks:    
  discord:
    name: discord-bots
volumes:
  discord_sticky_bot: 
