version: "3.9"
services:
  fail2ban_jail_envsubst:
    build:
      context: ./build/input_output_envsubst
      args:
        FILE_EXTENSION: "conf"
    env_file:
      - ../.ports.env
    volumes:
      - ./data/configs/fail2ban/template/jail.d:/mnt/input
      - ./data/configs/fail2ban/jail.d:/mnt/output
    network_mode: none
    cap_drop:
      - ALL
    cap_add:
      - CAP_DAC_OVERRIDE
      - CAP_FOWNER
    restart: on-failure
  fail2ban:
    build:
      context: ./build/fail2ban 
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    command: '-f -x -v'
    volumes:
      - ./data/configs/fail2ban/jail.d:/etc/fail2ban/jail.d
      - rsyslog_logs:/logs:ro
    depends_on:
      fail2ban_jail_envsubst:
        condition: service_completed_successfully
      rsyslog:
       condition: service_healthy
    blkio_config:
      weight: 500
      device_write_bps:
        - path: ${DISK}
          rate: '30m'
      device_read_bps:
        - path: ${DISK}
          rate: '60m'
      device_read_iops:
        - path: ${DISK}
          rate: 100
      device_write_iops:
        - path: ${DISK}
          rate: 100
    cpu_shares: 512
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M
    restart: unless-stopped
