version: "3.9"
x-defaults: &defaults
  depends_on:
    nginx_production: 
      condition: service_healthy
    nginx_development:
      condition: service_healthy
    gmod_permissions:
      condition: service_completed_successfully
  blkio_config:
    weight: 500
    device_write_bps:
      - path: ${DISK}
        rate: 60000000
    device_read_bps:
      - path: ${DISK}
        rate: 60000000
    device_read_iops:
      - path: ${DISK}
        rate: 200
    device_write_iops:
      - path: ${DISK}
        rate: 200
x-unionfs: &unionfs
  image: ethorbit/unionfs:latest
  <<: *defaults
  privileged: true
  network_mode: none
  environment:
    PUID: ${srcds_u}
    PGID: ${gmod_g}
    TZ: ${TZ}
  cpu_shares: 256
  deploy:
    resources:
      limits:
        memory: 50M
  restart: unless-stopped
x-gmod-environment: &gmod-environment
  SRCDS_APPID: 4020

x-gmod: &gmod
  build:
    context: ./build/srcds-server
    args:
      PUID: ${srcds_u}
      PGID: ${gmod_g}
      UMASK: "007"
      TZ: ${TZ}
  <<: *defaults
  stdin_open: true
  tty: true
  environment:
    <<: *gmod-environment
  cpu_count: 1
  cpu_shares: 1024
  deploy:
    resources:
      limits:
        memory: 512M
      reservations:
        memory: 256M
  networks:
    - gmod
  restart: unless-stopped
networks:
  gmod:
    driver: "bridge"
services:
  gmod_permissions:
    image: alpine:3.17.2
    volumes:
      - gmod_shared:/mnt/shared
      - gmod_1:/mnt/1
      - gmod_2:/mnt/2
      - gmod_3:/mnt/3
    command: >
      /bin/sh -c 'for d in shared 1 2 3; do 
      chown "${srcds_u}":"${gmod_g}" /mnt/$$d 
      chmod 2770 /mnt/$$d; 
      done'
    cap_drop:
      - ALL
    cap_add:
      - CAP_DAC_OVERRIDE
      - CHOWN
      - CAP_FOWNER
      - CAP_FSETID
    network_mode: none
    restart: on-failure
  unionfs-1:
    <<: *unionfs
    cpuset: "0"
    volumes:
      - ./data/users/passwd:/etc/passwd:ro
      - ./data/users/group:/etc/group:ro
      - ./data/users/shadow:/etc/shadow:ro
      - gmod_shared:/bottom:shared
      - gmod_1:/top:shared
      - gmod_1_merged:/merged:shared
  gmod-1:
    <<: *gmod
    cpuset: "${GMOD_1_CPU}"
    cpu_shares: 1024
    environment:
      <<: *gmod-environment
      SRCDS_RUN_ARGS: "-tickrate 33 -disableluarefresh -port 27015 +maxplayers 15 +gamemode sandbox +map gm_flatgrass"
    volumes:
      - ./data/users/passwd:/etc/passwd:ro
      - ./data/users/group:/etc/group:ro
      - ./data/users/shadow:/etc/shadow:ro
      - ./data/users/gshadow:/etc/gshadow:ro
      - gmod_1:/home/srcds/server
    ports:
      - 27015:27015/udp
    depends_on:
      unionfs-1:
        condition: service_started 
  unionfs-2:
    <<: *unionfs
    cpuset: "${GMOD_2_CPU}"
    volumes:
      - ./data/users/passwd:/etc/passwd:ro
      - ./data/users/group:/etc/group:ro
      - ./data/users/shadow:/etc/shadow:ro
      - gmod_shared:/bottom:shared
      - gmod_2:/top:shared
      - gmod_2_merged:/merged:shared
  gmod-2:
    <<: *gmod
    cpuset: "${GMOD_2_CPU}"
    cpu_shares: 1024
    environment:
      <<: *gmod-environment
      SRCDS_RUN_ARGS: "-tickrate 33 -disableluarefresh -port 27016 +maxplayers 15 +gamemode sandbox +map gm_flatgrass"
    volumes:
      - ./data/users/passwd:/etc/passwd:ro
      - ./data/users/group:/etc/group:ro
      - ./data/users/shadow:/etc/shadow:ro
      - ./data/users/gshadow:/etc/gshadow:ro
      - gmod_2:/home/srcds/server
    ports:
      - 27016:27016/udp
    depends_on:
      unionfs-2:
        condition: service_started 
  unionfs-3:
    <<: *unionfs
    cpuset: "${GMOD_3_CPU}"
    volumes:
      - ./data/users/passwd:/etc/passwd:ro
      - ./data/users/group:/etc/group:ro
      - ./data/users/shadow:/etc/shadow:ro
      - gmod_shared:/bottom:shared
      - gmod_3:/top:shared
      - gmod_3_merged:/merged:shared
  gmod-3:
    <<: *gmod
    cpuset: "${GMOD_3_CPU}"
    cpu_shares: 256
    environment:
      <<: *gmod-environment
      SRCDS_RUN_ARGS: "-tickrate 33 -disableluarefresh -port 27017 +maxplayers 15 +gamemode sandbox +map gm_flatgrass"
    volumes:
      - ./data/users/passwd:/etc/passwd:ro
      - ./data/users/group:/etc/group:ro
      - ./data/users/shadow:/etc/shadow:ro
      - ./data/users/gshadow:/etc/gshadow:ro
      - gmod_3:/home/srcds/server
    ports:
      - 27017:27017/udp
    depends_on:
      unionfs-3:
        condition: service_started 
volumes:
  gmod_shared:   
  gmod_1: 
  gmod_1_merged:   
  gmod_2: 
  gmod_2_merged:   
  gmod_3: 
  gmod_3_merged: 
