# Gmod clusters are named in nato phonetic alphabet 
# alpha, bravo, charlie, delta, echo, etc
# Each cluster can have any # of servers and are added as needed
# Each cluster has its own management group, team and database
# 
# The reasoning behind this is that gamemodes are kinda like separate games
version: "3.9"
x-defaults: &defaults
  extra_hosts:
    - "${DOMAIN_NAME}:172.10.1.2"
    - "${WEBSITE_SUBDOMAIN}.${DOMAIN_NAME}:172.10.1.2"
    - "${FASTDL_SUBDOMAIN}.${DOMAIN_NAME}:172.10.1.2"
  blkio_config:
    weight: 500
    device_write_bps:
      - path: ${DISK}
        rate: '60m'
    device_read_bps:
      - path: ${DISK}
        rate: '60m'
    device_read_iops:
      - path: ${DISK}
        rate: 1000
    device_write_iops:
      - path: ${DISK}
        rate: 1000

x-defaults-depends: &defaults_depends
  rsyslog:
    condition: service_healthy

x-defaults_development_depends: &defaults_development_depends
  <<: [ *defaults_depends ]
  nginx_development:
    condition: service_healthy
x-defaults_production_depends: &defaults_production_depends
  <<: [ *defaults_depends ]
  nginx_production: 
    condition: service_healthy

x-defaults_alpha_depends: &defaults_alpha_depends
  gmod_alpha_permissions:
    condition: service_completed_successfully
x-defaults_bravo_depends: &defaults_bravo_depends
  gmod_bravo_permissions:
    condition: service_completed_successfully
x-defaults_charlie_depends: &defaults_charlie_depends
  gmod_charlie_permissions:
    condition: service_completed_successfully

x-defaults_alpha_development: &defaults_alpha_development
  <<: *defaults
  depends_on:
    <<: [ *defaults_development_depends, *defaults_alpha_depends ]
x-defaults_alpha_production: &defaults_alpha_production
  <<: *defaults
  depends_on:
    <<: [ *defaults_production_depends, *defaults_alpha_depends ]

x-defaults_bravo_development: &defaults_bravo_development
  <<: *defaults
  depends_on:
    <<: [ *defaults_development_depends, *defaults_bravo_depends ]
x-defaults_bravo_production: &defaults_bravo_production
  <<: *defaults
  depends_on:
    <<: [ *defaults_production_depends, *defaults_bravo_depends ]

x-defaults_charlie_development: &defaults_charlie_development
  <<: *defaults
  depends_on:
    <<: [ *defaults_development_depends, *defaults_charlie_depends ]
x-defaults_charlie_production: &defaults_charlie_production
  <<: *defaults
  depends_on:
    <<: [ *defaults_production_depends, *defaults_charlie_depends ]

x-gmod-alpha: &gmod_alpha
  build:
    context: ./build/gmod-server
    args:
      PUID: ${steam_u}
      PGID: ${gmod_alpha_g}
  <<: [ *defaults ]
  stdin_open: true
  tty: true
  cpu_count: 1
  cpu_shares: 1024
  mem_limit: ${GMOD_ALPHA_RAM:-660M}
  hostname: gmod_alpha
  labels:
    - "com.docker-tc.enabled=1"
    - "com.docker-tc.limit=${GMOD_BANDWIDTH:-15mbps}"
    - "io.portainer.accesscontrol.teams=gmod_alpha"
  restart: always
x-gmod-bravo: &gmod_bravo
  build:
    context: ./build/gmod-server
    args:
      PUID: ${steam_u}
      PGID: ${gmod_bravo_g}
  <<: [ *defaults ]
  stdin_open: true
  tty: true
  cpu_count: 1
  cpu_shares: 1024
  mem_limit: ${GMOD_BRAVO_RAM:-660M}
  hostname: gmod_bravo
  labels:
    - "com.docker-tc.enabled=1"
    - "com.docker-tc.limit=${GMOD_BANDWIDTH:-15mbps}"
    - "io.portainer.accesscontrol.teams=gmod_bravo"
  restart: always
x-gmod-charlie: &gmod_charlie
  build:
    context: ./build/gmod-server
    args:
      PUID: ${steam_u}
      PGID: ${gmod_charlie_g}
  <<: [ *defaults ]
  stdin_open: true
  tty: true
  cpu_count: 1
  cpu_shares: 1024
  mem_limit: ${GMOD_CHARLIE_RAM:-660M}
  hostname: gmod_charlie
  labels:
    - "com.docker-tc.enabled=1"
    - "com.docker-tc.limit=${GMOD_BANDWIDTH:-15mbps}"
    - "io.portainer.accesscontrol.teams=gmod_charlie"
  restart: always
x-gmod_alpha_development: &gmod_alpha_development
  <<: [ *gmod_alpha, *defaults_alpha_development ]
x-gmod_alpha_production: &gmod_alpha_production
  <<: [ *gmod_alpha, *defaults_alpha_production ]
x-gmod_bravo_development: &gmod_bravo_development
  <<: [ *gmod_bravo, *defaults_bravo_development ]
x-gmod_bravo_production: &gmod_bravo_production
  <<: [ *gmod_bravo, *defaults_bravo_production ]
x-gmod_charlie_development: &gmod_charlie_development
  <<: [ *gmod_charlie, *defaults_charlie_development ]
x-gmod_charlie_production: &gmod_charlie_production
  <<: [ *gmod_charlie, *defaults_charlie_production ]
x-gmod_networks: &gmod_networks
  nginx:
  mysql:
x-gmod_alpha_env: &gmod_alpha_env
  UMASK: "007" 
  RCON_PASSWORD: ${GMOD_ALPHA_PASSWORD} 
x-gmod_bravo_env: &gmod_bravo_env
  UMASK: "007" 
  RCON_PASSWORD: ${GMOD_BRAVO_PASSWORD} 
x-gmod_charlie_env: &gmod_charlie_env
  UMASK: "007" 
  RCON_PASSWORD: ${GMOD_CHARLIE_PASSWORD} 

x-gmod_alpha_1: &gmod_alpha_1
  networks:
    gmod:
      ipv4_address: 172.150.1.1
    <<: [ *gmod_networks ]
  cpuset: ${GMOD_ALPHA_1_CPU}
  cpus: ${GMOD_ALPHA_1_CPU_FRACTION:-1}
  cpu_shares: 1024
  environment:
    <<: [ *gmod_alpha_env ]
    PORT: ${GMOD_ALPHA_1_PORT:-27015}
    STEAM_LOGIN_TOKEN: ${GMOD_ALPHA_1_LOGIN_TOKEN}
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./data/configs/users/passwd:/etc/passwd:ro
    - ./data/configs/users/group:/etc/group:ro
    - ./data/configs/users/shadow:/etc/shadow:ro
    - ./data/configs/users/gshadow:/etc/gshadow:ro
    - ${MOUNT_PROC_CPUINFO}:/proc/cpuinfo:rw
    - ${MOUNT_PROC_MEMINFO}:/proc/meminfo:rw
    - ${MOUNT_PROC_SWAPS}:/proc/swaps:rw
    - ${MOUNT_PROC_STAT}:/proc/stat:rw
    - ${MOUNT_PROC_DISKSTATS}:/proc/diskstats:rw
    - ${MOUNT_PROC_UPTIME}:/proc/uptime:rw
    - ${MOUNT_PROC_SLABINFO}:/proc/slabinfo:rw
    - ${MOUNT_SYS_DEVICES_SYSTEM_CPU}:/sys/devices/system/cpu:rw
    - gmod_alpha_1:${MOUNT_GUEST_STEAMCMD_GAMES}
    - gmod_alpha_shared:/shared
  ports:
    - ${GMOD_ALPHA_1_PORT:-27015}:${GMOD_ALPHA_1_PORT:-27015}/udp
    - ${GMOD_ALPHA_1_PORT:-27015}:${GMOD_ALPHA_1_PORT:-27015}/tcp
  logging:
    driver: syslog
    options:
      mode: non-blocking
      syslog-address: "tcp://localhost:${RSYSLOG_PORT}"
      tag: "gmod_alpha_1"

x-gmod_alpha_2: &gmod_alpha_2
  networks:
    gmod:
      ipv4_address: 172.150.1.2
    <<: [ *gmod_networks ]
  cpuset: ${GMOD_ALPHA_2_CPU}
  cpus: ${GMOD_ALPHA_2_CPU_FRACTION:-1}
  cpu_shares: 1024
  environment:
    <<: [ *gmod_alpha_env ]
    PORT: ${GMOD_ALPHA_2_PORT:-27016}
    STEAM_LOGIN_TOKEN: ${GMOD_ALPHA_2_LOGIN_TOKEN}
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./data/configs/users/passwd:/etc/passwd:ro
    - ./data/configs/users/group:/etc/group:ro
    - ./data/configs/users/shadow:/etc/shadow:ro
    - ./data/configs/users/gshadow:/etc/gshadow:ro
    - ${MOUNT_PROC_CPUINFO}:/proc/cpuinfo:rw
    - ${MOUNT_PROC_MEMINFO}:/proc/meminfo:rw
    - ${MOUNT_PROC_SWAPS}:/proc/swaps:rw
    - ${MOUNT_PROC_STAT}:/proc/stat:rw
    - ${MOUNT_PROC_DISKSTATS}:/proc/diskstats:rw
    - ${MOUNT_PROC_UPTIME}:/proc/uptime:rw
    - ${MOUNT_PROC_SLABINFO}:/proc/slabinfo:rw
    - ${MOUNT_SYS_DEVICES_SYSTEM_CPU}:/sys/devices/system/cpu:rw
    - gmod_alpha_2:${MOUNT_GUEST_STEAMCMD_GAMES}
    - gmod_alpha_shared:/shared
  ports:
    - ${GMOD_ALPHA_2_PORT:-27016}:${GMOD_ALPHA_2_PORT:-27016}/udp
    - ${GMOD_ALPHA_2_PORT:-27016}:${GMOD_ALPHA_2_PORT:-27016}/tcp
  logging:
    driver: syslog
    options:
      mode: non-blocking
      syslog-address: "tcp://localhost:${RSYSLOG_PORT}"
      tag: "gmod_alpha_2"

x-gmod_alpha_3: &gmod_alpha_3
  networks:
    gmod:
      ipv4_address: 172.150.1.3
    <<: [ *gmod_networks ]
  cpuset: ${GMOD_ALPHA_3_CPU}
  cpus: ${GMOD_ALPHA_3_CPU_FRACTION:-1}
  cpu_shares: 1024
  environment:
    <<: [ *gmod_alpha_env ]
    PORT: ${GMOD_ALPHA_3_PORT:-27017}
    STEAM_LOGIN_TOKEN: ${GMOD_ALPHA_3_LOGIN_TOKEN}
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./data/configs/users/passwd:/etc/passwd:ro
    - ./data/configs/users/group:/etc/group:ro
    - ./data/configs/users/shadow:/etc/shadow:ro
    - ./data/configs/users/gshadow:/etc/gshadow:ro
    - ${MOUNT_PROC_CPUINFO}:/proc/cpuinfo:rw
    - ${MOUNT_PROC_MEMINFO}:/proc/meminfo:rw
    - ${MOUNT_PROC_SWAPS}:/proc/swaps:rw
    - ${MOUNT_PROC_STAT}:/proc/stat:rw
    - ${MOUNT_PROC_DISKSTATS}:/proc/diskstats:rw
    - ${MOUNT_PROC_UPTIME}:/proc/uptime:rw
    - ${MOUNT_PROC_SLABINFO}:/proc/slabinfo:rw
    - ${MOUNT_SYS_DEVICES_SYSTEM_CPU}:/sys/devices/system/cpu:rw
    - gmod_alpha_3:${MOUNT_GUEST_STEAMCMD_GAMES}
    - gmod_alpha_shared:/shared
  ports:
    - ${GMOD_ALPHA_3_PORT:-27017}:${GMOD_ALPHA_3_PORT:-27017}/udp
    - ${GMOD_ALPHA_3_PORT:-27017}:${GMOD_ALPHA_3_PORT:-27017}/tcp
  logging:
    driver: syslog
    options:
      mode: non-blocking
      syslog-address: "tcp://localhost:${RSYSLOG_PORT}"
      tag: "gmod_alpha_3"

x-gmod_bravo_1: &gmod_bravo_1
  networks:
    gmod:
      ipv4_address: 172.150.1.10
    <<: [ *gmod_networks ]
  cpuset: ${GMOD_BRAVO_1_CPU}
  cpus: ${GMOD_BRAVO_1_CPU_FRACTION:-1}
  cpu_shares: 1024
  environment:
    <<: [ *gmod_bravo_env ]
    PORT: ${GMOD_BRAVO_1_PORT:-27025}
    STEAM_LOGIN_TOKEN: ${GMOD_BRAVO_1_LOGIN_TOKEN}
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./data/configs/users/passwd:/etc/passwd:ro
    - ./data/configs/users/group:/etc/group:ro
    - ./data/configs/users/shadow:/etc/shadow:ro
    - ./data/configs/users/gshadow:/etc/gshadow:ro
    - ${MOUNT_PROC_CPUINFO}:/proc/cpuinfo:rw
    - ${MOUNT_PROC_MEMINFO}:/proc/meminfo:rw
    - ${MOUNT_PROC_SWAPS}:/proc/swaps:rw
    - ${MOUNT_PROC_STAT}:/proc/stat:rw
    - ${MOUNT_PROC_DISKSTATS}:/proc/diskstats:rw
    - ${MOUNT_PROC_UPTIME}:/proc/uptime:rw
    - ${MOUNT_PROC_SLABINFO}:/proc/slabinfo:rw
    - ${MOUNT_SYS_DEVICES_SYSTEM_CPU}:/sys/devices/system/cpu:rw
    - gmod_bravo_1:${MOUNT_GUEST_STEAMCMD_GAMES}
    - gmod_bravo_shared:/shared
  ports:
    - ${GMOD_BRAVO_1_PORT:-27025}:${GMOD_BRAVO_1_PORT:-27025}/udp
    - ${GMOD_BRAVO_1_PORT:-27025}:${GMOD_BRAVO_1_PORT:-27025}/tcp
  logging:
    driver: syslog
    options:
      mode: non-blocking
      syslog-address: "tcp://localhost:${RSYSLOG_PORT}"
      tag: "gmod_bravo_1"

x-gmod_charlie_1: &gmod_charlie_1
  networks:
    gmod:
      ipv4_address: 172.150.1.20
    <<: [ *gmod_networks ]
  cpuset: ${GMOD_CHARLIE_1_CPU}
  cpus: ${GMOD_CHARLIE_1_CPU_FRACTION:-1}
  cpu_shares: 1024
  environment:
    <<: [ *gmod_charlie_env ]
    PORT: ${GMOD_CHARLIE_1_PORT:-27035}
    STEAM_LOGIN_TOKEN: ${GMOD_CHARLIE_1_LOGIN_TOKEN}
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./data/configs/users/passwd:/etc/passwd:ro
    - ./data/configs/users/group:/etc/group:ro
    - ./data/configs/users/shadow:/etc/shadow:ro
    - ./data/configs/users/gshadow:/etc/gshadow:ro
    - ${MOUNT_PROC_CPUINFO}:/proc/cpuinfo:rw
    - ${MOUNT_PROC_MEMINFO}:/proc/meminfo:rw
    - ${MOUNT_PROC_SWAPS}:/proc/swaps:rw
    - ${MOUNT_PROC_STAT}:/proc/stat:rw
    - ${MOUNT_PROC_DISKSTATS}:/proc/diskstats:rw
    - ${MOUNT_PROC_UPTIME}:/proc/uptime:rw
    - ${MOUNT_PROC_SLABINFO}:/proc/slabinfo:rw
    - ${MOUNT_SYS_DEVICES_SYSTEM_CPU}:/sys/devices/system/cpu:rw
    - gmod_charlie_1:${MOUNT_GUEST_STEAMCMD_GAMES}
    - gmod_charlie_shared:/shared
  ports:
    - ${GMOD_CHARLIE_1_PORT:-27035}:${GMOD_CHARLIE_1_PORT:-27035}/udp
    - ${GMOD_CHARLIE_1_PORT:-27035}:${GMOD_CHARLIE_1_PORT:-27035}/tcp
  logging:
    driver: syslog
    options:
      mode: non-blocking
      syslog-address: "tcp://localhost:${RSYSLOG_PORT}"
      tag: "gmod_charlie_1"

services:
  gmod_alpha_permissions:
    build:
      context: ./build/permissions
    volumes:
      - gmod_alpha_shared:/mnt/shared
      - gmod_alpha_1:/mnt/1
      - gmod_alpha_2:/mnt/2
      - gmod_alpha_3:/mnt/3
    command: >
      /bin/sh -c 'for d in shared 1 2 3; do 
      chown "${steam_u}":"${gmod_alpha_g}" "/mnt/$$d" 
      && chmod 2770 "/mnt/$$d" 
      && setfacl -d -m u::rwx,g::rwx,o::- "/mnt/$$d"; 
      done'
    cap_drop:
      - ALL
    cap_add:
      - CAP_DAC_OVERRIDE
      - CAP_CHOWN
      - CAP_FOWNER
      - CAP_FSETID
    network_mode: none
    restart: on-failure
  gmod_bravo_permissions:
    build:
      context: ./build/permissions
    volumes:
      - gmod_bravo_shared:/mnt/shared
      - gmod_bravo_1:/mnt/1
    command: >
      /bin/sh -c 'for d in shared 1; do 
      chown "${steam_u}":"${gmod_bravo_g}" "/mnt/$$d" 
      && chmod 2770 "/mnt/$$d" 
      && setfacl -d -m u::rwx,g::rwx,o::- "/mnt/$$d"; 
      done'
    cap_drop:
      - ALL
    cap_add:
      - CAP_DAC_OVERRIDE
      - CAP_CHOWN
      - CAP_FOWNER
      - CAP_FSETID
    network_mode: none
    restart: on-failure
  gmod_charlie_permissions:
    build:
      context: ./build/permissions
    volumes:
      - gmod_charlie_shared:/mnt/shared
      - gmod_charlie_1:/mnt/1
    command: >
      /bin/sh -c 'for d in shared 1; do 
      chown "${steam_u}":"${gmod_charlie_g}" "/mnt/$$d" 
      && chmod 2770 "/mnt/$$d" 
      && setfacl -d -m u::rwx,g::rwx,o::- "/mnt/$$d"; 
      done'
    cap_drop:
      - ALL
    cap_add:
      - CAP_DAC_OVERRIDE
      - CAP_CHOWN
      - CAP_FOWNER
      - CAP_FSETID
    network_mode: none
    restart: on-failure
  gmod_alpha_1_production:
    profiles:
      - production
    <<: [ *gmod_alpha_production, *gmod_alpha_1 ]
  # gmod_alpha_2_production:
  #   profiles:
  #     - production
  #   <<: [ *gmod_alpha_production, *gmod_alpha_2 ]
  # gmod_alpha_3_production:
  #   profiles:
  #     - production
  #   <<: [ *gmod_alpha_production, *gmod_alpha_3 ]
  gmod_alpha_1_development:
    profiles:
      - development
    <<: [ *gmod_alpha_development, *gmod_alpha_1 ]
  # gmod_alpha_2_development:
  #   profiles:
  #     - development
  #   <<: [ *gmod_alpha_development, *gmod_alpha_2 ]
  # gmod_alpha_3_development:
  #   profiles:
  #     - development
  #   <<: [ *gmod_alpha_development, *gmod_alpha_3 ]
  # gmod_bravo_1_production:
  #   profiles:
  #     - production
  #   <<: [ *gmod_bravo_production, *gmod_bravo_1 ]
  # gmod_bravo_1_development:
  #   profiles:
  #     - development
  #   <<: [ *gmod_bravo_development, *gmod_bravo_1 ]
  # gmod_charlie_1_production:
  #   profiles:
  #     - production
  #   <<: [ *gmod_charlie_production, *gmod_charlie_1 ]
  # gmod_charlie_1_development:
  #   profiles:
  #     - development
  #   <<: [ *gmod_charlie_development, *gmod_charlie_1 ]
  
volumes:
  gmod_alpha_shared:
  gmod_bravo_shared:
  gmod_charlie_shared:
  gmod_alpha_1:
  gmod_alpha_2:
  gmod_alpha_3:
  gmod_bravo_1:
  gmod_charlie_1:
networks:
  gmod:
    ipam:
      driver: default 
      config:
        - subnet: 172.150.0.0/22
