version: "3.9"
x-defaults: &defaults
  depends_on:
    nginx_production: 
      condition: service_healthy
    nginx_development:
      condition: service_healthy
    gmod_permissions:
      condition: service_completed_successfully
  blkio_config:
    weight: 500
    device_write_bps:
      - path: ${DISK}
        rate: 60000000
    device_read_bps:
      - path: ${DISK}
        rate: 60000000
    device_read_iops:
      - path: ${DISK}
        rate: 200
    device_write_iops:
      - path: ${DISK}
        rate: 200

#x-unionfs: &unionfs
#  #image: ethorbit/unionfs:latest
#  build:
#    context: ./build/unionfs
#  <<: *defaults
#  privileged: true
#  network_mode: none
#  environment:
#    PUID: ${steam_u}
#    PGID: ${gmod_g}
#    TZ: ${TZ}
#    MERGED_DIR_NAME: server
#  cpu_shares: 256
#  deploy:
#    resources:
#      limits:
#        memory: 50M
#  restart: unless-stopped
x-mergerfs: &mergerfs 
  image: hotio/mergerfs
  network_mode: none
  init: true
  privileged: true
  environment:
    - PUID=${steam_u}
    - PGID=${gmod_g}
    - UMASK=007
    - TZ=${TZ}
  devices:
    - /dev/fuse
  command: "-o allow_other,default_permissions,\
    nonempty,minfreespace=0,category.create=mfs,\
    category.search=mfs,category.action=mfs \
    /branch_1=RW:/branch_2=RO /mountpoint"
  cpu_shares: 256
  deploy:
    resources:
      limits:
        memory: 50M
  restart: unless-stopped

x-gmod-environment: &gmod-environment
  SRCDS_APPID: 4020

x-gmod: &gmod
  build:
    context: ./build/gmod-server
    args:
      PUID: ${steam_u}
      PGID: ${gmod_g}
      UMASK: "007"
      TZ: ${TZ}
  <<: *defaults
  stdin_open: true
  tty: true
  environment:
    <<: *gmod-environment
  cpu_count: 1
  cpu_shares: 1024
  deploy:
    resources:
      limits:
        memory: 512M
      reservations:
        memory: 256M
  networks:
    - gmod
  restart: unless-stopped
networks:
  gmod:
    driver: "bridge"
services:
  gmod_permissions:
    image: alpine:3.17.2
    volumes:
      - gmod_shared:/mnt/shared
      - gmod_1:/mnt/1
      - gmod_2:/mnt/2
      - gmod_3:/mnt/3
      - ./data/mounts/gmod_1_merged:/mnt/1_merged
      - ./data/mounts/gmod_2_merged:/mnt/2_merged
      - ./data/mounts/gmod_3_merged:/mnt/3_merged
    command: >
      /bin/sh -c 'for d in shared 1 2 3 1_merged 2_merged 3_merged; do 
      chown "${steam_u}":"${gmod_g}" /mnt/$$d && 
      chmod 2770 /mnt/$$d; 
      done'
    cap_drop:
      - ALL
    cap_add:
      - CAP_DAC_OVERRIDE
      - CAP_CHOWN
      - CAP_FOWNER
      - CAP_FSETID
    network_mode: none
    restart: on-failure
#  unionfs-1:
#    <<: *unionfs
#    cpuset: "0"
#    volumes:
#      - ./data/users/passwd:/etc/passwd:ro
#      - ./data/users/group:/etc/group:ro
#      - ./data/users/shadow:/etc/shadow:ro
#      - gmod_shared:/bottom
#      - gmod_1:/top
#      - ./data/mounts/gmod_1_merged:/merged:rshared
  mergerfs-1: 
    <<: *mergerfs
    volumes:
      - ./data/users/passwd:/etc/passwd:ro
      - ./data/users/group:/etc/group:ro
      - ./data/users/shadow:/etc/shadow:ro
      - gmod_1:/branch_1
      - gmod_shared:/branch_2:ro
      - ./data/mounts/gmod_1_merged:/mountpoint:rshared
  gmod-1:
    <<: *gmod
    cpuset: "${GMOD_1_CPU}"
    cpu_shares: 1024
    environment:
      <<: *gmod-environment
      START_ARGS: "-tickrate 33 -disableluarefresh -port 27015 +maxplayers 15 +gamemode sandbox +map gm_flatgrass"
    volumes:
      - ./data/users/passwd:/etc/passwd:ro
      - ./data/users/group:/etc/group:ro
      - ./data/users/shadow:/etc/shadow:ro
      - ./data/users/gshadow:/etc/gshadow:ro
      - ./data/mounts/gmod_1_merged:/home/steam/server
    ports:
      - 27015:27015/udp
    depends_on:
      mergerfs-1:
        condition: service_started
#  mergerfs-2: 
#    <<: *mergerfs
#    volumes:
#      - ./data/users/passwd:/etc/passwd:ro
#      - ./data/users/group:/etc/group:ro
#      - ./data/users/shadow:/etc/shadow:ro
#      - gmod_shared:/branch_1
#      - gmod_2:/branch_2
#      - ./data/mounts/gmod_2_merged:/mountpoint:rshared
#  gmod-2:
#    <<: *gmod
#    cpuset: "${GMOD_2_CPU}"
#    cpu_shares: 1024
#    environment:
#      <<: *gmod-environment
#      SRCDS_RUN_ARGS: "-tickrate 33 -disableluarefresh -port 27016 +maxplayers 15 +gamemode sandbox +map gm_flatgrass"
#    volumes:
#      - ./data/users/passwd:/etc/passwd:ro
#      - ./data/users/group:/etc/group:ro
#      - ./data/users/shadow:/etc/shadow:ro
#      - ./data/users/gshadow:/etc/gshadow:ro
#      - ./data/mounts/gmod_2_merged:/home/steam/server
#    ports:
#      - 27016:27016/udp
#    depends_on:
#      mergerfs-2:
#        condition: service_started
#  mergerfs-3: 
#    <<: *mergerfs
#    volumes:
#      - ./data/users/passwd:/etc/passwd:ro
#      - ./data/users/group:/etc/group:ro
#      - ./data/users/shadow:/etc/shadow:ro
#      - gmod_shared:/branch_1
#      - gmod_3:/branch_2
#      - ./data/mounts/gmod_3_merged:/mountpoint:rshared
#  gmod-3:
#    <<: *gmod
#    cpuset: "${GMOD_3_CPU}"
#    cpu_shares: 256
#    environment:
#      <<: *gmod-environment
#      SRCDS_RUN_ARGS: "-tickrate 33 -disableluarefresh -port 27017 +maxplayers 15 +gamemode sandbox +map gm_flatgrass"
#    volumes:
#      - ./data/users/passwd:/etc/passwd:ro
#      - ./data/users/group:/etc/group:ro
#      - ./data/users/shadow:/etc/shadow:ro
#      - ./data/users/gshadow:/etc/gshadow:ro
#      - ./data/mounts/gmod_3_merged:/home/steam/server
#    ports:
#      - 27017:27017/udp
#    depends_on:
#      mergerfs-2:
#        condition: service_started
volumes:
  gmod_shared:   
  gmod_1: 
  gmod_2: 
  gmod_3: 
