version: "3.9"
x-defaults: &defaults
  blkio_config:
    weight: 500
    device_write_bps:
      - path: ${DISK}
        rate: '60m'
    device_read_bps:
      - path: ${DISK}
        rate: '60m'
    device_read_iops:
      - path: ${DISK}
        rate: 5000
    device_write_iops:
      - path: ${DISK}
        rate: 5000
x-defaults_depends: &defaults_depends
  gmod_permissions:
    condition: service_completed_successfully
  rsyslog:
    condition: service_healthy
x-defaults_development: &defaults_development
  <<: *defaults
  depends_on:
    <<: [ *defaults_depends ]
    nginx_development:
      condition: service_healthy
x-defaults_production: &defaults_production
  <<: *defaults
  depends_on:
    <<: [ *defaults_depends ]
    nginx_production: 
      condition: service_healthy
    
x-gmod: &gmod
  build:
    context: ./build/gmod-server
    args:
      PUID: ${steam_u}
      PGID: ${gmod_g}
  <<: [ *defaults ]
  stdin_open: true
  tty: true
  cpu_count: 1
  cpu_shares: 1024
  deploy:
    resources:
      limits:
        memory: 660M
      reservations:
        memory: 256M
  hostname: gmod
  extra_hosts:
    - "${DOMAIN_NAME}:172.10.1.2"
    - "${WEBSITE_SUBDOMAIN}.${DOMAIN_NAME}:172.10.1.2"
    - "${FASTDL_SUBDOMAIN}.${DOMAIN_NAME}:172.10.1.2"
  labels:
    - "io.portainer.accesscontrol.teams=gmod"
  restart: always
x-gmod_development: &gmod_development
  <<: [ *gmod, *defaults_development ]
x-gmod_production: &gmod_production
  <<: [ *gmod, *defaults_production ]
x-gmod_env: &gmod_env
  UMASK: "007" 
  RCON_PASSWORD: ${GMOD_PASSWORD} 
x-gmod_networks: &gmod_networks
  nginx:
  mysql:

x-gmod_1: &gmod_1
  networks:
    gmod:
      ipv4_address: 172.150.1.1
    <<: [ *gmod_networks ]
  cpuset: "${GMOD_1_CPU}"
  cpu_shares: 1024
  environment:
    <<: [ *gmod_env ]
    PORT: ${GMOD_1_PORT:-27015}
    STEAM_LOGIN_TOKEN: ${GMOD_1_LOGIN_TOKEN}
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./data/configs/users/passwd:/etc/passwd:ro
    - ./data/configs/users/group:/etc/group:ro
    - ./data/configs/users/shadow:/etc/shadow:ro
    - ./data/configs/users/gshadow:/etc/gshadow:ro
    - /var/lib/lxcfs/proc/cpuinfo:/proc/cpuinfo:rw
    - /var/lib/lxcfs/proc/diskstats:/proc/diskstats:rw
    - /var/lib/lxcfs/proc/meminfo:/proc/meminfo:rw
    - /var/lib/lxcfs/proc/stat:/proc/stat:rw
    - /var/lib/lxcfs/proc/swaps:/proc/swaps:rw
    - /var/lib/lxcfs/proc/uptime:/proc/uptime:rw
    - /var/lib/lxcfs/proc/slabinfo:/proc/slabinfo:rw
    - /var/lib/lxcfs/sys/devices/system/cpu:/sys/devices/system/cpu:rw
    - gmod_1:/home/steam/server:slave
    - gmod_shared:/shared:slave
  ports:
    - ${GMOD_1_PORT:-27015}:${GMOD_1_PORT:-27015}/udp
    - ${GMOD_1_PORT:-27015}:${GMOD_1_PORT:-27015}/tcp
  logging:
    driver: syslog
    options:
      mode: non-blocking
      syslog-address: "tcp://localhost:${RSYSLOG_PORT}"
      tag: "gmod_1"

x-gmod_2: &gmod_2
  networks:
    gmod:
      ipv4_address: 172.150.1.2
    <<: [ *gmod_networks ]
  cpuset: "${GMOD_2_CPU}"
  cpu_shares: 1024
  environment:
    <<: [ *gmod_env ]
    PORT: ${GMOD_2_PORT:-27016}
    STEAM_LOGIN_TOKEN: ${GMOD_2_LOGIN_TOKEN}
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./data/configs/users/passwd:/etc/passwd:ro
    - ./data/configs/users/group:/etc/group:ro
    - ./data/configs/users/shadow:/etc/shadow:ro
    - ./data/configs/users/gshadow:/etc/gshadow:ro
    - /var/lib/lxcfs/proc/cpuinfo:/proc/cpuinfo:rw
    - /var/lib/lxcfs/proc/diskstats:/proc/diskstats:rw
    - /var/lib/lxcfs/proc/meminfo:/proc/meminfo:rw
    - /var/lib/lxcfs/proc/stat:/proc/stat:rw
    - /var/lib/lxcfs/proc/swaps:/proc/swaps:rw
    - /var/lib/lxcfs/proc/uptime:/proc/uptime:rw
    - /var/lib/lxcfs/proc/slabinfo:/proc/slabinfo:rw
    - /var/lib/lxcfs/sys/devices/system/cpu:/sys/devices/system/cpu:rw
    - gmod_2:/home/steam/server:slave
    - gmod_shared:/shared:slave
  ports:
    - ${GMOD_2_PORT:-27016}:${GMOD_2_PORT:-27016}/udp
    - ${GMOD_2_PORT:-27016}:${GMOD_2_PORT:-27016}/tcp
  logging:
    driver: syslog
    options:
      mode: non-blocking
      syslog-address: "tcp://localhost:${RSYSLOG_PORT}"
      tag: "gmod_2"

x-gmod_3: &gmod_3
  networks:
    gmod:
      ipv4_address: 172.150.1.3
    <<: [ *gmod_networks ]
  cpuset: "${GMOD_3_CPU}"
  cpu_shares: 1024
  environment:
    <<: [ *gmod_env ]
    PORT: ${GMOD_3_PORT:-27017}
    STEAM_LOGIN_TOKEN: ${GMOD_3_LOGIN_TOKEN}
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./data/configs/users/passwd:/etc/passwd:ro
    - ./data/configs/users/group:/etc/group:ro
    - ./data/configs/users/shadow:/etc/shadow:ro
    - ./data/configs/users/gshadow:/etc/gshadow:ro
    - /var/lib/lxcfs/proc/cpuinfo:/proc/cpuinfo:rw
    - /var/lib/lxcfs/proc/diskstats:/proc/diskstats:rw
    - /var/lib/lxcfs/proc/meminfo:/proc/meminfo:rw
    - /var/lib/lxcfs/proc/stat:/proc/stat:rw
    - /var/lib/lxcfs/proc/swaps:/proc/swaps:rw
    - /var/lib/lxcfs/proc/uptime:/proc/uptime:rw
    - /var/lib/lxcfs/proc/slabinfo:/proc/slabinfo:rw
    - /var/lib/lxcfs/sys/devices/system/cpu:/sys/devices/system/cpu:rw
    - gmod_3:/home/steam/server:slave
    - gmod_shared:/shared:slave
  ports:
    - ${GMOD_3_PORT:-27017}:${GMOD_3_PORT:-27017}/udp
    - ${GMOD_3_PORT:-27017}:${GMOD_3_PORT:-27017}/tcp
  logging:
    driver: syslog
    options:
      mode: non-blocking
      syslog-address: "tcp://localhost:${RSYSLOG_PORT}"
      tag: "gmod_3"

services:
  gmod_permissions:
    build:
      context: ./build/permissions
    volumes:
      - gmod_shared:/mnt/shared
      - gmod_1:/mnt/1
      - gmod_2:/mnt/2
      - gmod_3:/mnt/3
    command: >
      /bin/sh -c 'for d in shared 1 2 3; do 
      chown "${steam_u}":"${gmod_g}" "/mnt/$$d" 
      && chmod 2770 "/mnt/$$d" 
      && setfacl -d -m u::rwx,g::rwx,o::- "/mnt/$$d"; 
      done'
    cap_drop:
      - ALL
    cap_add:
      - CAP_DAC_OVERRIDE
      - CAP_CHOWN
      - CAP_FOWNER
      - CAP_FSETID
    network_mode: none
    restart: on-failure
  gmod_1_production:
    profiles:
      - production
    <<: [ *gmod_production, *gmod_1 ]
  gmod_2_production:
    profiles:
      - production
    <<: [ *gmod_production, *gmod_2 ]
  gmod_3_production:
    profiles:
      - production
    <<: [ *gmod_production, *gmod_3 ]
  gmod_1_development:
    profiles:
      - development
    <<: [ *gmod_development, *gmod_1 ]
  gmod_2_development:
    profiles:
      - development
    <<: [ *gmod_development, *gmod_2 ]
  gmod_3_development:
    profiles:
      - development
    <<: [ *gmod_development, *gmod_3 ]

volumes:
  gmod_shared:
  gmod_1:
  gmod_2:
  gmod_3:
networks:
  gmod:
    ipam:
      driver: default 
      config:
        - subnet: 172.150.1.0/22
