version: "3.9"
x-defaults: &defaults
  depends_on:
    nginx_production: 
      condition: service_healthy
    nginx_development:
      condition: service_healthy
    gmod_permissions:
      condition: service_completed_successfully
  blkio_config:
    weight: 500
    device_write_bps:
      - path: ${DISK}
        rate: 60000000
    device_read_bps:
      - path: ${DISK}
        rate: 60000000
    device_read_iops:
      - path: ${DISK}
        rate: 200
    device_write_iops:
      - path: ${DISK}
        rate: 200
x-gmod: &gmod
  build:
    context: ./build/gmod-server
    args:
      PUID: ${steam_u}
      PGID: ${gmod_g}
      UMASK: "007"
      SHARED_DIR: "/shared/garrysmod"
  <<: *defaults
  stdin_open: true
  tty: true
  cpu_count: 1
  cpu_shares: 1024
  deploy:
    resources:
      limits:
        memory: 512M
      reservations:
        memory: 256M
  networks:
    - gmod
  restart: unless-stopped
networks:
  gmod:
    driver: "bridge"
services:
  gmod_permissions:
    image: alpine:3.17.2
    volumes:
      - gmod_shared:/mnt/shared
      - gmod_1:/mnt/1
      - gmod_2:/mnt/2
      - gmod_3:/mnt/3
    command: >
      /bin/sh -c 'for d in shared 1 2 3; do 
      chown "${steam_u}":"${gmod_g}" "/mnt/$$d" && 
      chmod 2770 "/mnt/$$d"; 
      done'
    cap_drop:
      - ALL
    cap_add:
      - CAP_DAC_OVERRIDE
      - CAP_CHOWN
      - CAP_FOWNER
      - CAP_FSETID
    network_mode: none
    restart: on-failure
  gmod-1:
    <<: *gmod
    cpuset: "${GMOD_1_CPU}"
    cpu_shares: 1024
    environment:
      - PORT=27015
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/users/passwd:/etc/passwd:ro
      - ./data/users/group:/etc/group:ro
      - ./data/users/shadow:/etc/shadow:ro
      - ./data/users/gshadow:/etc/gshadow:ro
      - gmod_1:/home/steam/server:slave
      - gmod_shared:/shared:slave
    ports:
      - 27015:27015/udp
  gmod-2:
    <<: *gmod
    cpuset: "${GMOD_2_CPU}"
    cpu_shares: 1024
    environment:
      - PORT=27016
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/users/passwd:/etc/passwd:ro
      - ./data/users/group:/etc/group:ro
      - ./data/users/shadow:/etc/shadow:ro
      - ./data/users/gshadow:/etc/gshadow:ro
      - gmod_2:/home/steam/server:slave
      - gmod_shared:/shared:slave
    ports:
      - 27016:27016/udp
  gmod-3:
    <<: *gmod
    cpuset: "${GMOD_3_CPU}"
    cpu_shares: 256
    environment:
      - PORT=27017
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/users/passwd:/etc/passwd:ro
      - ./data/users/group:/etc/group:ro
      - ./data/users/shadow:/etc/shadow:ro
      - ./data/users/gshadow:/etc/gshadow:ro
      - gmod_3:/home/steam/server:slave
      - gmod_shared:/shared:slave
    ports:
      - 27017:27017/udp
volumes:
  gmod_shared:
  gmod_1:
  gmod_2:
  gmod_3:
