version: "3.9"
x-hl2dm: &hl2dm
  build:
    context: ./build/hl2dm-server
    args:
      PUID: ${steam_u}
      PGID: ${hl2dm_g}
      UMASK: "007"
  tty: true
  stdin_open: true
  environment:
    START_ARGS: "-port ${HL2DM_PORT:-27315} +maxplayers 12 +map dm_lockdown"
    PORT: ${HL2DM_PORT:-27315}
    STEAM_LOGIN_TOKEN: ${HL2DM_LOGIN_TOKEN}
    RCON_PASSWORD: ${HL2DM_PASSWORD}
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./data/configs/users/passwd:/etc/passwd:ro
    - ./data/configs/users/group:/etc/group:ro
    - ./data/configs/users/shadow:/etc/shadow:ro
    - ./data/configs/users/gshadow:/etc/gshadow:ro
    - ${MOUNT_PROC_CPUINFO}:/proc/cpuinfo:rw
    - ${MOUNT_PROC_MEMINFO}:/proc/meminfo:rw
    - ${MOUNT_PROC_SWAPS}:/proc/swaps:rw
    - ${MOUNT_PROC_STAT}:/proc/stat:rw
    - ${MOUNT_PROC_DISKSTATS}:/proc/diskstats:rw
    - ${MOUNT_PROC_UPTIME}:/proc/uptime:rw
    - ${MOUNT_PROC_SLABINFO}:/proc/slabinfo:rw
    - ${MOUNT_SYS_DEVICES_SYSTEM_CPU}:/sys/devices/system/cpu:rw
    - hl2dm:${MOUNT_GUEST_STEAMCMD_GAMES}
  ports:
    - ${HL2DM_PORT:-27315}:${HL2DM_PORT:-27315}/udp
    - ${HL2DM_PORT:-27315}:${HL2DM_PORT:-27315}/tcp
  networks:
    hl2dm:
      ipv4_address: 172.153.1.1
    nginx:
    mysql:
  extra_hosts:
    - "${DOMAIN_NAME}:172.10.1.2"
    - "${WEBSITE_SUBDOMAIN}.${DOMAIN_NAME}:172.10.1.2"
    - "${FASTDL_SUBDOMAIN}.${DOMAIN_NAME}:172.10.1.2"
  hostname: hl2dm
  labels:
    - "io.portainer.accesscontrol.teams=hl2dm"
  cpuset: ${HL2DM_CPU}
  cpu_count: 1
  cpu_shares: 256
  deploy:
    resources:
      limits:
        memory: 512M 
      reservations:
        memory: 128M  
  blkio_config:
    weight: 150
    device_write_bps:
      - path: ${DISK}
        rate: '60m'
    device_read_bps:
      - path: ${DISK}
        rate: '60m'
    device_read_iops:
      - path: ${DISK}
        rate: 1000
    device_write_iops:
      - path: ${DISK}
        rate: 1000
  logging:
    driver: syslog
    options:
      mode: non-blocking
      syslog-address: "tcp://localhost:${RSYSLOG_PORT}"
      tag: "hl2dm"
  restart: always
x-hl2dm-depends: &hl2dm-depends
  hl2dm_permissions:
    condition: service_completed_successfully
  rsyslog:
    condition: service_healthy

services:
  hl2dm_permissions:
    build:
      context: ./build/permissions
    volumes:
      - hl2dm:/mnt
    command: >
      /bin/sh -c 'chown "${steam_u}":"${hl2dm_g}" /mnt 
      && chmod 2770 /mnt 
      && setfacl -d -m u::rwx,g::rwx,o::- /mnt'
    cap_drop:
      - ALL 
    cap_add:
      - CAP_DAC_OVERRIDE
      - CAP_CHOWN
      - CAP_FOWNER
      - CAP_FSETID
    network_mode: none
    restart: on-failure
  hl2dm_production:
    profiles:
      - production
    <<: [ *hl2dm ]
    depends_on:
      <<: [ *hl2dm-depends ]
      nginx_production: 
        condition: service_healthy
  hl2dm_development:
    profiles:
      - development
    <<: [ *hl2dm ]
    depends_on:
      <<: [ *hl2dm-depends ]
      nginx_development:
        condition: service_healthy
volumes:
  hl2dm:
networks: 
  hl2dm:
    ipam:
      driver: default 
      config:
        - subnet: 172.153.1.0/22
