# HL2DM clusters are named in nato phonetic alphabet 
# alpha, bravo, charlie, delta, echo, etc
# Each cluster can have any # of servers and are added as needed
# Each cluster has its own management group, team and database
# 
# The reasoning behind this is that gamemodes are kinda like separate games
version: "3.9"

x-hl2dm-rsyslog: &hl2dm_rsyslog
  command: '-n'
  tty: true
  stdin_open: true
  healthcheck:
    test: "/healthcheck.sh"
    start_period: 5s
    interval: 5s
    timeout: 10s
    retries: 3
  restart: always

x-hl2dm: &hl2dm
  tty: true
  stdin_open: true
  extra_hosts:
    - "${DOMAIN_NAME}:172.10.1.2"
    - "${WEBSITE_SUBDOMAIN}.${DOMAIN_NAME}:172.10.1.2"
    - "${FASTDL_SUBDOMAIN}.${DOMAIN_NAME}:172.10.1.2"
  cpu_count: 1
  cpu_shares: 256
  deploy:
    resources:
      limits:
        memory: 512M
      reservations:
        memory: 128M
  blkio_config:
    weight: 150
    device_write_bps:
      - path: ${DISK}
        rate: '60m'
    device_read_bps:
      - path: ${DISK}
        rate: '60m'
    device_read_iops:
      - path: ${DISK}
        rate: 1000
    device_write_iops:
      - path: ${DISK}
        rate: 1000

x-hl2dm-networks: &hl2dm_networks
  nginx:
  mysql:

x-hl2dm-alpha: &hl2dm_alpha
  <<: [ *hl2dm ]
  build:
    context: ./build/hl2dm-server
    args:
      PUID: ${steam_u}
      PGID: ${hl2dm_alpha_g}
      UMASK: "007"
  labels:
    - "io.portainer.accesscontrol.teams=hl2dm_alpha"

x-hl2dm-bravo: &hl2dm_bravo
  <<: [ *hl2dm ]
  build:
    context: ./build/hl2dm-server
    args:
      PUID: ${steam_u}
      PGID: ${hl2dm_bravo_g}
      UMASK: "007"
  labels:
    - "io.portainer.accesscontrol.teams=hl2dm_bravo"

x-hl2dm-alpha-1: &hl2dm_alpha_1
  <<: [ *hl2dm_alpha ]
  environment:
    START_ARGS: "-port ${HL2DM_ALPHA_1_PORT:-27315} +maxplayers 12 +map dm_lockdown"
    PORT: ${HL2DM_ALPHA_1_PORT:-27315}
    STEAM_LOGIN_TOKEN: ${HL2DM_ALPHA_LOGIN_TOKEN}
    RCON_PASSWORD: ${HL2DM_ALPHA_PASSWORD}
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./data/configs/users/passwd:/etc/passwd:ro
    - ./data/configs/users/group:/etc/group:ro
    - ./data/configs/users/shadow:/etc/shadow:ro
    - ./data/configs/users/gshadow:/etc/gshadow:ro
    - ${MOUNT_PROC_CPUINFO}:/proc/cpuinfo:rw
    - ${MOUNT_PROC_MEMINFO}:/proc/meminfo:rw
    - ${MOUNT_PROC_SWAPS}:/proc/swaps:rw
    - ${MOUNT_PROC_STAT}:/proc/stat:rw
    - ${MOUNT_PROC_DISKSTATS}:/proc/diskstats:rw
    - ${MOUNT_PROC_UPTIME}:/proc/uptime:rw
    - ${MOUNT_PROC_SLABINFO}:/proc/slabinfo:rw
    - ${MOUNT_SYS_DEVICES_SYSTEM_CPU}:/sys/devices/system/cpu:rw
    - hl2dm_alpha_1:${MOUNT_GUEST_STEAMCMD_GAMES}
    - hl2dm_alpha_shared:/shared
  ports:
    - ${HL2DM_ALPHA_1_PORT:-27315}:${HL2DM_ALPHA_1_PORT:-27315}/udp
    - ${HL2DM_ALPHA_1_PORT:-27315}:${HL2DM_ALPHA_1_PORT:-27315}/tcp
  networks:
    hl2dm:
      ipv4_address: 172.153.1.1
    <<: [ *hl2dm_networks ]
  hostname: hl2dm_alpha_1
  cpuset: ${HL2DM_ALPHA_1_CPU}
  logging:
    driver: syslog
    options:
      mode: non-blocking
      syslog-address: "tcp://localhost:${HL2DM_ALPHA_RSYSLOG_PORT}"
      tag: "hl2dm_alpha_1"
  restart: always

x-hl2dm-bravo-1: &hl2dm_bravo_1
  <<: [ *hl2dm_bravo ]
  environment:
    START_ARGS: "-port ${HL2DM_BRAVO_1_PORT:-27325} +maxplayers 12 +map dm_lockdown"
    PORT: ${HL2DM_BRAVO_1_PORT:-27325}
    STEAM_LOGIN_TOKEN: ${HL2DM_BRAVO_LOGIN_TOKEN}
    RCON_PASSWORD: ${HL2DM_BRAVO_PASSWORD}
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./data/configs/users/passwd:/etc/passwd:ro
    - ./data/configs/users/group:/etc/group:ro
    - ./data/configs/users/shadow:/etc/shadow:ro
    - ./data/configs/users/gshadow:/etc/gshadow:ro
    - ${MOUNT_PROC_CPUINFO}:/proc/cpuinfo:rw
    - ${MOUNT_PROC_MEMINFO}:/proc/meminfo:rw
    - ${MOUNT_PROC_SWAPS}:/proc/swaps:rw
    - ${MOUNT_PROC_STAT}:/proc/stat:rw
    - ${MOUNT_PROC_DISKSTATS}:/proc/diskstats:rw
    - ${MOUNT_PROC_UPTIME}:/proc/uptime:rw
    - ${MOUNT_PROC_SLABINFO}:/proc/slabinfo:rw
    - ${MOUNT_SYS_DEVICES_SYSTEM_CPU}:/sys/devices/system/cpu:rw
    - hl2dm_bravo_1:${MOUNT_GUEST_STEAMCMD_GAMES}
    - hl2dm_bravo_shared:/shared
  ports:
    - ${HL2DM_BRAVO_1_PORT:-27325}:${HL2DM_BRAVO_1_PORT:-27325}/udp
    - ${HL2DM_BRAVO_1_PORT:-27325}:${HL2DM_BRAVO_1_PORT:-27325}/tcp
  networks:
    hl2dm:
      ipv4_address: 172.153.1.10
    <<: [ *hl2dm_networks ]
  hostname: hl2dm_bravo_1
  cpuset: ${HL2DM_BRAVO_1_CPU}
  logging:
    driver: syslog
    options:
      mode: non-blocking
      syslog-address: "tcp://localhost:${HL2DM_BRAVO_RSYSLOG_PORT}"
      tag: "hl2dm_bravo_1"
  restart: always

x-hl2dm-production: &hl2dm_production
  profiles:
    - production

x-hl2dm-development: &hl2dm_development
  profiles:
    - development
    
x-hl2dm-development-depends: &hl2dm_development_depends
  nginx_development:
    condition: service_healthy

x-hl2dm-production-depends: &hl2dm_production_depends
  nginx_production: 
    condition: service_healthy
      
x-hl2dm-alpha-depends: &hl2dm_alpha_depends
  hl2dm_alpha_rsyslog:
    condition: service_healthy
  hl2dm_alpha_permissions:
    condition: service_completed_successfully
 
x-hl2dm-bravo-depends: &hl2dm_bravo_depends
  hl2dm_bravo_rsyslog:
    condition: service_healthy
  hl2dm_bravo_permissions:
    condition: service_completed_successfully
 
x-hl2dm-permissions: &hl2dm_permissions
  build:
    context: ./build/permissions
  cap_drop:
    - ALL 
  cap_add:
    - CAP_DAC_OVERRIDE
    - CAP_CHOWN
    - CAP_FOWNER
    - CAP_FSETID
  network_mode: none
  restart: on-failure

services:
  hl2dm_alpha_permissions:
    <<: [ *hl2dm_permissions ]
    volumes:
      - hl2dm_alpha_shared:/mnt/shared
      - hl2dm_alpha_1:/mnt/1
    command: >
      /bin/sh -c 'for d in shared 1; do 
      chown "${steam_u}":"${hl2dm_alpha_g}" "/mnt/$$d" 
      && chmod 2770 "/mnt/$$d" 
      && setfacl -d -m u::rwx,g::rwx,o::- "/mnt/$$d"; 
      done'
  hl2dm_bravo_permissions:
    <<: [ *hl2dm_permissions ]
    volumes:
      - hl2dm_bravo_shared:/mnt/shared
      - hl2dm_bravo_1:/mnt/1
    command: >
      /bin/sh -c 'for d in shared 1; do 
      chown "${steam_u}":"${hl2dm_bravo_g}" "/mnt/$$d" 
      && chmod 2770 "/mnt/$$d" 
      && setfacl -d -m u::rwx,g::rwx,o::- "/mnt/$$d"; 
      done'
      
  hl2dm_alpha_1_production:
    <<: [ *hl2dm_alpha_1, *hl2dm_production ]
    depends_on:
      <<: [ *hl2dm_production_depends, *hl2dm_alpha_depends ]
  hl2dm_alpha_1_development:
    <<: [ *hl2dm_alpha_1, *hl2dm_development ]
    depends_on:
      <<: [ *hl2dm_development_depends, *hl2dm_alpha_depends ]
  
  hl2dm_bravo_1_production:
    <<: [ *hl2dm_bravo_1, *hl2dm_production ]
    depends_on:
      <<: [ *hl2dm_production_depends, *hl2dm_bravo_depends ]
  hl2dm_bravo_1_development:
    <<: [ *hl2dm_bravo_1, *hl2dm_development ]
    depends_on:
      <<: [ *hl2dm_development_depends, *hl2dm_bravo_depends ]

  hl2dm_alpha_rsyslog:
    <<: [ *hl2dm_rsyslog ]
    build:
      context: ./build/rsyslog
      args:
        - UID=${rsyslog_u}
        - GID=${hl2dm_alpha_g}
        - PORT=${HL2DM_ALPHA_RSYSLOG_PORT}
    hostname: rsyslog_hl2dm_alpha
    ports:
      - 127.0.0.1:${HL2DM_ALPHA_RSYSLOG_PORT}:${HL2DM_ALPHA_RSYSLOG_PORT}/tcp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/configs/rsyslog/rsyslog.conf:/etc/rsyslog.conf
      - ./data/configs/logrotate/rsyslog.conf:/etc/logrotate.d/rsyslog
      - hl2dm_alpha_logs:/logs
  hl2dm_bravo_rsyslog:
    <<: [ *hl2dm_rsyslog ]
    build:
      context: ./build/rsyslog
      args:
        - UID=${rsyslog_u}
        - GID=${hl2dm_bravo_g}
        - PORT=${HL2DM_BRAVO_RSYSLOG_PORT}
    hostname: rsyslog_hl2dm_bravo
    ports:
      - 127.0.0.1:${HL2DM_BRAVO_RSYSLOG_PORT}:${HL2DM_BRAVO_RSYSLOG_PORT}/tcp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/configs/rsyslog/rsyslog.conf:/etc/rsyslog.conf
      - ./data/configs/logrotate/rsyslog.conf:/etc/logrotate.d/rsyslog
      - hl2dm_bravo_logs:/logs

volumes:
  hl2dm_alpha_logs:
  hl2dm_bravo_logs:
  hl2dm_alpha_shared:
  hl2dm_bravo_shared:
  hl2dm_alpha_1:
  hl2dm_bravo_1:
networks: 
  hl2dm:
    ipam:
      driver: default 
      config:
        - subnet: 172.153.1.0/22
