version: "3.9"
services:
  mysql_envsubst:
    build:
      context: ./build/input_output_envsubst
      args:
        FILE_EXTENSION: "sql"
    env_file:
      - ../.users.env
    environment:
      - MYSQL_HOST=172.212.0.%
    volumes:
      - ./data/configs/mysql/template:/mnt/input
      - ./data/configs/mysql:/mnt/output
    network_mode: none
    cap_drop:
      - ALL
    cap_add:
      - CAP_DAC_OVERRIDE
      - CAP_FOWNER
    restart: on-failure
  mysql:
    build:
      context: ./build/mysql
      args:
        - UID=${mysql_u}
        - GID=${admin_g}
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    networks:
      mysql:
        ipv4_address: 172.212.1.1
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${MOUNT_PROC_CPUINFO}:/proc/cpuinfo:rw
      - ${MOUNT_PROC_MEMINFO}:/proc/meminfo:rw
      - ${MOUNT_PROC_SWAPS}:/proc/swaps:rw
      - ${MOUNT_PROC_STAT}:/proc/stat:rw
      - ${MOUNT_PROC_DISKSTATS}:/proc/diskstats:rw
      - ${MOUNT_PROC_UPTIME}:/proc/uptime:rw
      - ${MOUNT_PROC_SLABINFO}:/proc/slabinfo:rw
      - ${MOUNT_SYS_DEVICES_SYSTEM_CPU}:/sys/devices/system/cpu:rw
      - mysql:/var/lib/mysql
      - ./data/configs/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/configs/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      #- /dev/null:/etc/mysql/conf.d/docker.cnf
    ports:
      - 127.0.0.1:${MYSQL_PORT:-3306}:3306/tcp
    depends_on:
      mysql_envsubst:
        condition: service_completed_successfully
      mysql_rsyslog:
        condition: service_healthy
    logging:
      driver: syslog
      options:
        mode: non-blocking
        syslog-address: "tcp://localhost:${MYSQL_RSYSLOG_PORT}"
        tag: "mysql"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    cpuset: ${MYSQL_CPU}
    cpu_shares: 1024
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 512M
    blkio_config:
      weight: 1000
      device_write_bps:
        - path: ${DISK}
          rate: '250m'
      device_read_bps:
        - path: ${DISK}
          rate: '250m'
      device_read_iops:
        - path: ${DISK}
          rate: 4000
      device_write_iops:
        - path: ${DISK}
          rate: 4000
    restart: always

  mysql_rsyslog:
    command: '-n'
    tty: true
    stdin_open: true
    healthcheck:
      test: "/healthcheck.sh"
      start_period: 5s
      interval: 5s
      timeout: 10s
      retries: 3
    restart: always
    build:
      context: ./build/rsyslog
      args:
        - UID=${rsyslog_u}
        - GID=${mysql_g}
        - PORT=${MYSQL_RSYSLOG_PORT}
    hostname: rsyslog_mysql
    ports:
      - 127.0.0.1:${MYSQL_RSYSLOG_PORT}:${MYSQL_RSYSLOG_PORT}/tcp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/configs/rsyslog/rsyslog.conf:/etc/rsyslog.conf
      - mysql_logs:/logs
volumes:
  mysql_logs:
  mysql:
networks:
  mysql:
    ipam:
      driver: default 
      config:
        - subnet: 172.212.1.0/22
