version: "3.9"

x-limits: &limits
  cpuset: ${MYSQL_CPU}
  cpu_shares: 1024
  deploy:
    resources:
      limits:
        memory: ${MYSQL_RAM:-2048M}
      reservations:
        memory: 512M
  blkio_config:
    weight: 1000
    device_write_bps:
      - path: ${DISK}
        rate: '250m'
    device_read_bps:
      - path: ${DISK}
        rate: '250m'
    device_read_iops:
      - path: ${DISK}
        rate: 4000
    device_write_iops:
      - path: ${DISK}
        rate: 4000

services:
  mysql_envsubst:
    build:
      context: ./build/input_output_envsubst
      args:
        FILE_EXTENSION: "sql"
    env_file:
      - ../.users.env
    environment:
      - MYSQL_HOST=172.212.0.%
    volumes:
      - ./data/configs/mysql/template:/mnt/input
      - ./data/configs/mysql:/mnt/output
    network_mode: none
    cap_drop:
      - ALL
    cap_add:
      - CAP_DAC_OVERRIDE
      - CAP_FOWNER
    restart: on-failure
  mysql:
    build:
      context: ./build/mysql
      args:
        - UID=${mysql_u}
        - GID=${admin_g}
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    networks:
      mysql:
        ipv4_address: 172.212.1.1
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${ADMIN_PASSWORD}
    healthcheck:
      test: "mysqladmin ping -h 127.0.0.1 --silent || exit 1"
      start_period: 5s
      interval: 5s
      timeout: 10s
      retries: 3
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${MOUNT_PROC_CPUINFO}:/proc/cpuinfo:rw
      - ${MOUNT_PROC_MEMINFO}:/proc/meminfo:rw
      - ${MOUNT_PROC_SWAPS}:/proc/swaps:rw
      - ${MOUNT_PROC_STAT}:/proc/stat:rw
      - ${MOUNT_PROC_DISKSTATS}:/proc/diskstats:rw
      - ${MOUNT_PROC_UPTIME}:/proc/uptime:rw
      - ${MOUNT_PROC_SLABINFO}:/proc/slabinfo:rw
      - ${MOUNT_SYS_DEVICES_SYSTEM_CPU}:/sys/devices/system/cpu:rw
      - mysql:/var/lib/mysql
      - mysql_backups:/mnt/backups
      - ./data/configs/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/configs/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      #- /dev/null:/etc/mysql/conf.d/docker.cnf
    ports:
      - 127.0.0.1:${MYSQL_PORT:-3306}:3306/tcp
    depends_on:
      mysql_envsubst:
        condition: service_completed_successfully
      rsyslog:
        condition: service_healthy
    logging:
      driver: syslog
      options:
        mode: non-blocking
        syslog-address: "tcp://localhost:${RSYSLOG_PORT}"
        tag: "mysql"
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    <<: [ *limits ]
    restart: always

  mysql_backups:
    build:
      context: ./build/mysql-anacron-backup
      args:
        UID: ${mysql_u}
        GID: ${admin_g}
    networks:
      - mysql
    extra_hosts:
      - "mysql:172.212.1.1"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_USER: admin
      MYSQL_PASS: ${ADMIN_PASSWORD}
      ANACRON_DAYS: 7
      MAX_BACKUPS: 26
      GZIP_LEVEL: 9
      MYSQLDUMP_OPTS: --no-tablespaces
    volumes:
      - mysql_backups:/backup
      - mysql_backups_spool:/home/mysql-backup/.anacron/spool
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ${MOUNT_PROC_CPUINFO}:/proc/cpuinfo:rw
      - ${MOUNT_PROC_MEMINFO}:/proc/meminfo:rw
      - ${MOUNT_PROC_SWAPS}:/proc/swaps:rw
      - ${MOUNT_PROC_STAT}:/proc/stat:rw
      - ${MOUNT_PROC_DISKSTATS}:/proc/diskstats:rw
      - ${MOUNT_PROC_UPTIME}:/proc/uptime:rw
      - ${MOUNT_PROC_SLABINFO}:/proc/slabinfo:rw
      - ${MOUNT_SYS_DEVICES_SYSTEM_CPU}:/sys/devices/system/cpu:rw
    logging:
      driver: syslog
      options:
        mode: non-blocking
        syslog-address: "tcp://localhost:${RSYSLOG_PORT}"
        tag: "mysql_backups"
    depends_on:
      mysql:
        condition: service_healthy
      rsyslog:
        condition: service_healthy
    <<: [ *limits ]
    restart: always

volumes:
  mysql:
  mysql_backups:
  mysql_backups_spool:
networks:
  mysql:
    ipam:
      driver: default 
      config:
        - subnet: 172.212.1.0/22
