version: "3.9"
services:
  mysql_envsubst:
    build:
      context: ./build/input_output_envsubst
      args:
        FILE_EXTENSION: "sql"
    env_file:
      - ../.users.env
    volumes:
      - ./data/configs/mysql/template:/mnt/input
      - ./data/configs/mysql:/mnt/output
    network_mode: none
    cap_drop:
      - ALL
    cap_add:
      - CAP_DAC_OVERRIDE
      - CAP_FOWNER
    restart: on-failure
  mysql:
    image: mysql:8.0.32-debian
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    networks:
      - mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - mysql:/var/lib/mysql
      - ./data/configs/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    depends_on:
      mysql_envsubst:
        condition: service_completed_successfully
    restart: always
volumes:
  mysql:
networks:
  mysql:
