version: "3.9"
services:
  mysql_envsubst:
    build:
      context: ./build/input_output_envsubst
      args:
        FILE_EXTENSION: "sql"
    env_file:
      - ../.users.env
    volumes:
      - ./data/configs/mysql/template:/mnt/input
      - ./data/configs/mysql:/mnt/output
    network_mode: none
    cap_drop:
      - ALL
    cap_add:
      - CAP_DAC_OVERRIDE
      - CAP_FOWNER
    restart: on-failure
  mysql:
    image: mysql:8.0.32-debian
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    networks:
      - mysql
      - gmod
      - svencoop
    environment:
      - MYSQL_ROOT_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - mysql:/var/lib/mysql
      - ./data/configs/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 127.0.0.1:${MYSQL_PORT:-3306}:3306/tcp
    depends_on:
      mysql_envsubst:
        condition: service_completed_successfully
      rsyslog:
        condition: service_healthy
    logging:
      driver: syslog
      options:
        mode: non-blocking
        syslog-address: "tcp://localhost:${RSYSLOG_PORT}"
        tag: "mysql"
    blkio_config:
      weight: 1000
      device_write_bps:
        - path: ${DISK}
          rate: '250m'
      device_read_bps:
        - path: ${DISK}
          rate: '250m'
      device_read_iops:
        - path: ${DISK}
          rate: 4000
      device_write_iops:
        - path: ${DISK}
          rate: 4000
    restart: always
volumes:
  mysql:
networks:
  mysql:
