version: "3.9"
# TODO: add a healthcheck that ensures a website connection can be made
x-nginx: &nginx
  build:
    context: ./build/nginx
    args:
      UID: ${NGINX_UID}
      GID: ${NZC_GID}
  networks:
    - nginx
  ports:
    - ${NGINX_HTTP_PORT:-80}:80
    - ${NGINX_HTTPS_PORT:-443}:443
  cpuset: ${NGINX_CPU}
  cpu_shares: 2048
  deploy:
    resources:
      limits:
        memory: 1024M
      reservations:
        memory: 512M
  blkio_config:
    weight: 800
    device_write_bps:
      - path: ${DISK}
        rate: 50000000
    device_read_bps:
      - path: ${DISK}
        rate: 50000000
    device_read_iops:
      - path: ${DISK}
        rate: 100
    device_write_iops:
      - path: ${DISK}
        rate: 100
  restart: unless-stopped
x-nginx_envsubst: &nginx_envsubst
  image: ethorbit/envsubst:latest
  volumes:
    - ./data/nginx/snippets.template:/mnt/nginx_snippet_templates
    - ./data/nginx/snippets:/mnt/nginx_snippets
  command: >
    /bin/sh -c "find /mnt/nginx_snippet_templates
    -type f
    -name \"*.conf\"
    -exec /bin/sh -c 'envsubst < \"$0\" > /mnt/nginx_snippets/$(basename \"$0\")' {} \\;"
  network_mode: none
  cap_drop:
    - ALL
services:
  nginx_permissions:
    image: alpine:latest
    volumes:
      - nginx_websites:/mnt/nginx_websites
      - nginx_cpu:/mnt/nginx_cpu
      - ./data/nginx:/mnt/nginx_conf
      - mkcert:/mnt/mkcert
      - certbot_conf:/mnt/certbot_conf
      - certbot_www:/mnt/certbot_www
    command: >
      /bin/sh -c "echo \"${NGINX_CPU}\" > /mnt/nginx_cpu/online
      && mkdir -p /mnt/nginx_websites/fastdl
      && chown ${NGINX_UID}:${NGINX_GID} /mnt/nginx_websites/fastdl
      && chown -R root:root /mnt/nginx_conf/
      && chown -fR ${NGINX_UID}:root /mnt/mkcert/
      && if [ -f '/mnt/certbot_conf/ssl-dhparams.pem' ]; then
        chown -f ${NGINX_UID}:root /mnt/certbot_conf/ssl-dhparams.pem
      fi
      && if [ -d '/mnt/certbot_conf/live/' ]; then
        chown -fR ${NGINX_UID}:root /mnt/certbot_conf/live/
      fi"
    network_mode: none
    cap_drop:
      - ALL 
    cap_add:
      - CHOWN
    depends_on:
      certbot:
        condition: service_started
      mkcert:
        condition: service_completed_successfully
      openssl:
        condition: service_completed_successfully
    restart: on-failure
  # Production nginx, for use only on a machine the real domain is pointing to.
  certbot:
    image: certbot/certbot:latest
    profiles:
      - production
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    networks:
      - nginx
    restart: unless-stopped       
  nginx_envsubst_production:
    <<: *nginx_envsubst
    profiles:
      - production
    environment:  
      - DOMAIN_NAME="${DOMAIN_NAME}"
      - NGINX_SSL_CERT="/etc/letsencrypt/live/chronicles.local/cert.pem"
      - NGINX_SSL_CERT_KEY="/etc/letsencrypt/live/chronicles.local/privkey.pem"
      - NGINX_SSL_DHPARAM="/etc/letsencrypt/ssl-dhparams.pem"
  nginx_production: 
    <<: *nginx  
    profiles:
      - production
    volumes:  
      - nginx_cpu:/sys/devices/system/cpu:ro
      - nginx_websites:/usr/share/nginx/html   
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/snippets:/etc/nginx/snippets
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      #- svencoop:/usr/share/nginx/html/svencoop:ro
      - certbot_conf:/etc/letsencrypt    
      - certbot_www:/var/www/certbot 
    depends_on:
      nginx_envsubst_production:
        condition: service_completed_successfully
      nginx_permissions:
        condition: service_completed_successfully
  # Development nginx (because Let's Encrypt only works on the actual domain)
  # In your host's /etc/hosts, add: 127.0.0.1 chronicles.local
  # After running, add the .crt file located in the host's 
  # CA_TRUST_STORE_DIR into your browser.
  mkcert:
    image: ethorbit/mkcert:latest
    profiles:
      - development
    volumes:
      - ${CA_TRUST_STORE_DIR:-/usr/local/share/ca-certificates}:/usr/local/share/ca-certificates
      - mkcert:/mnt
    command: > 
      /bin/sh -c "[[ ! -s /mnt/mkcert.pem || ! -s /mnt/mkcert.key ]]
      && mkcert -install
      && mkcert -cert-file /mnt/mkcert.pem -key-file /mnt/mkcert.key
      ${DOMAIN_NAME} 
      || exit 0" 
    network_mode: none 
  openssl:
    image: ethorbit/openssl:latest
    profiles:
      - development
    volumes:
      - mkcert:/mnt
    command: >
      /bin/sh -c "[[ ! -s /mnt/mkcert.dh ]]
      && openssl dhparam -out /mnt/mkcert.dh 4096
      || exit 0"
  nginx_envsubst_development:
    <<: *nginx_envsubst
    profiles:
      - development
    environment:
      - DOMAIN_NAME="${DOMAIN_NAME}"
      - NGINX_SSL_CERT="/etc/mkcert/mkcert.pem"
      - NGINX_SSL_CERT_KEY="/etc/mkcert/mkcert.key"
      - NGINX_SSL_DHPARAM="/etc/mkcert/mkcert.dh"
  nginx_development:
    <<: *nginx
    profiles:
      - development
    volumes:   
      - nginx_cpu:/sys/devices/system/cpu:ro
      - nginx_websites:/usr/share/nginx/html 
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/snippets:/etc/nginx/snippets
      - ./data/nginx/conf.d:/etc/nginx/conf.d
        #- svencoop:/usr/share/nginx/html/fastdl/svencoop:ro
      - mkcert:/etc/mkcert
    extra_hosts:
      - "${DOMAIN_NAME}:127.0.0.1" 
    depends_on:
      nginx_envsubst_development:
        condition: service_completed_successfully
      nginx_permissions:
        condition: service_completed_successfully
volumes:
  nginx_cpu:
  nginx_websites:
  certbot_conf:
  certbot_www:
  mkcert:
networks:
  nginx:
