version: "3.9"
services:
  nginx:
    image: nginxinc/nginx-unprivileged:latest
    user: "${NGINX_UID}:${NZC_GID}"
    volumes:
      - svencoop:/usr/share/nginx/svencoop:ro
    ports:
      - ${NGINX_PORT}:8080
volumes:
  nginx:

#build:
#context: ./build/nginx/
#args:
#UID: ${NGINX_UID}
#GID: ${NGINX_GID} 
