version: "3.9"
services:
  #certbot:
  #  image: certbot/certbot:latest
  nginx_permissions:
    image: alpine:latest
    volumes:
      - ./data/nginx/conf.d:/mnt
    command: "chown -R root:root /mnt/"
    restart: on-failure
  nginx:
    build:
      context: ./build/nginx
      args:
        UID: ${NGINX_UID}
        GID: ${NZC_GID}
    volumes:
      - nginx_websites:/usr/share/nginx/html
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - svencoop:/usr/share/nginx/html/svencoop:ro
    ports:
      - ${NGINX_HTTP_PORT:-80}:80
      - ${NGINX_HTTPS_PORT:-443}:443
    depends_on:
      nginx_permissions:
        condition: service_completed_successfully
      #certbot:
        #condition: service_completed_successfully
    restart: unless-stopped
volumes:
  nginx_websites:
