version: "3.9"
# TODO: add a healthcheck that ensures a website connection can be made
x-nginx: &nginx
  build:
    context: ./build/nginx
    args:
      UID: ${NGINX_UID}
      GID: ${NZC_GID}
  networks:
    - nginx
  ports:
    - ${NGINX_HTTP_PORT:-80}:80
    - ${NGINX_HTTPS_PORT:-443}:443
  restart: unless-stopped
services: 
  nginx_permissions:
    image: alpine:latest
    volumes:
      - ./data/nginx/conf.d:/mnt/nginx_conf 
      - mkcert:/mnt/mkcert
      - certbot_conf:/mnt/certbot_conf
      - certbot_www:/mnt/certbot_www
    command: >
      /bin/sh -c "chown -R root:root /mnt/nginx_conf/ &&\
        chown -fR ${NGINX_UID}:root /mnt/mkcert/ &&\
        if [ -f '/mnt/certbot_conf/ssl-dhparams.pem' ]; then \
        chown -f ${NGINX_UID}:root /mnt/certbot_conf/ssl-dhparams.pem \
        fi &&\ 
        if [ -d '/mnt/certbot_conf/live/' ]; then \
        chown -fR ${NGINX_UID}:root /mnt/certbot_conf/live/ \
        fi"
    network_mode: none
    cap_drop:
      - ALL 
    cap_add:
      - CHOWN
    depends_on:
      certbot:
        condition: service_started
      mkcert:
        condition: service_completed_successfully
    restart: on-failure
  
  # Production nginx, for use only on the machine the desired domain is on.
  certbot:
    image: certbot/certbot:latest
    profiles:
      - production
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    networks:
      - nginx
    restart: unless-stopped       
  nginx_production: 
    <<: *nginx  
    profiles:
      - production
    volumes: 
      - nginx_websites:/usr/share/nginx/html
      - svencoop:/usr/share/nginx/html/svencoop:ro
      - ./data/nginx/conf.d:/etc/nginx/conf.d 
      - ./data/nginx/snippets:/etc/nginx/snippets
      - ./data/nginx/snippets/production:/etc/nginx/snippets/profile
      - certbot_conf:/etc/letsencrypt    
      - certbot_www:/var/www/certbot
    depends_on:  
      nginx_permissions:
        condition: service_completed_successfully
          
  # Development nginx (because Let's Encrypt only works on the actual domain)
  # In your host's /etc/hosts, add: 127.0.0.1 chronicles.local
  # After running, add the .crt file located in the host's 
  # CA_TRUST_STORE_DIR into your browser.
  mkcert:
    image: ethorbit/mkcert:latest
    profiles:
      - development
    volumes:
      - ${CA_TRUST_STORE_DIR:-/usr/local/share/ca-certificates}:/usr/local/share/ca-certificates
      - mkcert:/mnt
    command: > 
      /bin/sh -c '[[ ! -f /mnt/mkcert.pem ]] &&\
              mkcert -install &&\
              mkcert -cert-file /mnt/mkcert.pem \
              -key-file /mnt/mkcert.key \
              chronicles.local || exit 0' 
    network_mode: none
  nginx_development:
    <<: *nginx
    profiles:
      - development
    volumes:   
      - nginx_websites:/usr/share/nginx/html
      - svencoop:/usr/share/nginx/html/svencoop:ro
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/snippets:/etc/nginx/snippets
      - ./data/nginx/snippets/development:/etc/nginx/snippets/profile
      - mkcert:/etc/mkcert
    extra_hosts:
      - "chronicles.local:127.0.0.1"
    depends_on:  
      nginx_permissions:
        condition: service_completed_successfully
volumes:
  nginx_websites:
  certbot_conf:
  certbot_www:
  mkcert:
networks:
  nginx:
