version: "3.9"
services:
  nginx:
    #image: nginxinc/nginx-unprivileged:latest
    build:
      context: nginxinc/nginx-unprivileged:latest
      args:
        UID: ${NGINX_UID}
        GID: ${NGINX_GID} 
    volumes:
      - svencoop:/usr/share/nginx/svencoop
    ports:
      - ${NGINX_PORT}:8080
volumes:
  nginx:
