version: "3.9"
x-labels: &labels
  labels:
    - "io.portainer.accesscontrol.teams=websites"
 
x-nginx_dependencies: &nginx_dependencies
  dhparam:
    condition: service_completed_successfully
  rsyslog:
    condition: service_healthy

x-nginx: &nginx
  #container_name: ${CONTAINER_NAME_PREFIX}-nginx-${CONTAINER_NAME_SUFFIX}
  build:
    context: ./build/nginx
    args:
      UID: ${nginx_u}
      GID: ${nginx_g}
  user: ${nginx_u}:${nginx_g}
  group_add:
    - ${php_g}
    - ${svencoop_g}
    - ${synergy_g}
    - ${hl2dm_alpha_g}
    - ${hl2dm_bravo_g}
    - ${gmod_alpha_g}
    - ${gmod_bravo_g}
    - ${gmod_charlie_g}
    - ${ark_g}
    - ${websites_g}
  hostname: nginx
  ports:
    - ${NGINX_HTTP_PORT:-80}:80/tcp
    - ${NGINX_HTTPS_PORT:-443}:443/tcp
  env_file:
    - ../.domain.env
  extra_hosts:
    - "searxng:172.50.10.1"
    - "portainer:172.60.10.1"
  healthcheck:
    test: "curl -f http://127.0.0.1 || exit 1"
    start_period: 5s
    interval: 10s
    timeout: 10s
    retries: 3
  cpuset: ${NGINX_CPU}
  cpu_shares: 1024
  deploy:
    resources:
      limits:
        memory: ${NGINX_RAM:-1024M}
      reservations:
        memory: 512M
  blkio_config:
    weight: 800
    device_write_bps:
      - path: ${DISK}
        rate: '300m'
    device_read_bps:
      - path: ${DISK}
        rate: '300m'
    device_read_iops:
      - path: ${DISK}
        rate: 2000
    device_write_iops:
      - path: ${DISK}
        rate: 2000
  <<: [*labels]
  logging:
    driver: syslog
    options:
      mode: non-blocking
      syslog-address: "tcp://localhost:${RSYSLOG_PORT}"
      tag: "nginx"
  restart: always    
x-nginx_networks: &nginx_networks
  nginx:
    ipv4_address: 172.10.1.2
  searxng:
x-nginx_envsubst_conf: &nginx_envsubst_conf
  build:
    context: ./build/input_output_envsubst
    args:
      FILE_EXTENSION: "conf"
  volumes:
    - ./data/configs/nginx/template/conf.d:/mnt/input
    - ./data/configs/nginx/conf.d:/mnt/output
  network_mode: none
  cap_drop:
    - ALL
  cap_add:
    - CAP_DAC_OVERRIDE
    - CAP_FOWNER
  <<: [*labels]
  restart: on-failure
x-nginx_envsubst_snippets: &nginx_envsubst_snippets
  build:
    context: ./build/input_output_envsubst
    args:
      FILE_EXTENSION: "conf"
  volumes:
    - ./data/configs/nginx/template/snippets:/mnt/input
    - ./data/configs/nginx/snippets:/mnt/output
  network_mode: none
  cap_drop:
    - ALL
  cap_add:
    - CAP_DAC_OVERRIDE
    - CAP_FOWNER
  <<: [*labels]
  restart: on-failure
x-nginx_envsubst_environment: &nginx_envsubst_environment
  WEBSITES_ROOT: "/mnt/websites"
  FASTDL_ROOT: "/mnt/fastdl"
  PHPMYADMIN_ROOT: "/mnt/admin/phpmyadmin"
  NGINX_PORTAINER_CACHE_PATH: /mnt/cache/portainer
  NGINX_PHPMYADMIN_CACHE_PATH: /mnt/cache/phpmyadmin
  NGINX_SEARCH_CACHE_PATH: /mnt/cache/search
  NGINX_SSL_DHPARAM: "/etc/dhparam/dhparam.dh"

x-nginx_envsubst_production_environment: &nginx_envsubst_production_environment
  <<: [ *nginx_envsubst_environment ]
  NGINX_SSL_CERT: "/etc/letsencrypt/live/${DOMAIN_NAME}/cert.pem"
  NGINX_SSL_CERT_KEY: "/etc/letsencrypt/live/${DOMAIN_NAME}/privkey.pem"

x-nginx_envsubst_production: &nginx_envsubst_production
  profiles:
    - production
  env_file:
    - ../.ports.env
    - ../.domain.env
  environment:  
    <<: [ *nginx_envsubst_production_environment ]
  <<: [*labels]
  restart: on-failure

x-nginx_envsubst_development_environment: &nginx_envsubst_development_environment
  <<: [ *nginx_envsubst_environment ]
  NGINX_SSL_CERT: "/etc/mkcert/mkcert.pem"
  NGINX_SSL_CERT_KEY: "/etc/mkcert/mkcert.key"

x-nginx_envsubst_development: &nginx_envsubst_development
  profiles:
    - development
  env_file:
    - ../.ports.env
    - ../.domain.env
  environment:
    <<: [ *nginx_envsubst_development_environment ]
  restart: on-failure
services:
  nginx_links:
    image: alpine:3.17.2
    volumes:
      - nginx_fastdl:/mnt/fastdl
    command: >
      /bin/sh -c "mkdir -p /mnt/links/svencoop_shared
      && rm -f /mnt/fastdl/svencoop_shared
      && ln -sf /mnt/links/svencoop_shared /mnt/fastdl/svencoop_shared"
    cap_drop:
      - ALL 
    cap_add:
      - CAP_DAC_OVERRIDE
    network_mode: none
    <<: [*labels]
    restart: on-failure
  nginx_permissions:
    image: alpine:3.17.2
    build:
      context: ./build/permissions
    volumes: 
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/configs/users/passwd:/etc/passwd:ro
      - ./data/configs/users/group:/etc/group:ro
      - ./data/configs/users/shadow:/etc/shadow:ro
      - ./data/configs/users/gshadow:/etc/gshadow:ro
      - nginx_cache:/mnt/nginx_cache
      - nginx_websites:/mnt/nginx_websites
      - nginx_fastdl:/mnt/nginx_fastdl
      - ./data/configs/nginx/cpu:/mnt/nginx_cpu
      - ./data/configs/nginx:/mnt/nginx_conf
    command: >
      /bin/sh -c "chown ${nginx_u}:${websites_g} /mnt/nginx_websites
      && chown ${nginx_u}:${fastdl_g} /mnt/nginx_fastdl
      && chmod 2771 /mnt/nginx_websites 
      /mnt/nginx_fastdl
      && mkdir -p /mnt/nginx_cache/portainer
      && mkdir -p /mnt/nginx_cache/phpmyadmin
      && mkdir -p /mnt/nginx_cache/search
      && mkdir -p /mnt/admin/portainer
      && chmod 700 -R /mnt/nginx_cache/
      && chown -R ${nginx_u}:${nginx_g} /mnt/nginx_cache/
      && mkdir -p /mnt/nginx_fastdl/gmod_alpha /mnt/nginx_fastdl/gmod_bravo /mnt/nginx_fastdl/gmod_charlie
      && mkdir -p /mnt/nginx_fastdl/hl2dm_alpha /mnt/nginx_fastdl/hl2dm_bravo
      && mkdir -p /mnt/nginx_fastdl/synergy
      && chown ${nginx_u}:${synergy_g} /mnt/nginx_fastdl/synergy
      && chown ${nginx_u}:${hl2dm_alpha_g} /mnt/nginx_fastdl/hl2dm_alpha
      && chown ${nginx_u}:${hl2dm_bravo_g} /mnt/nginx_fastdl/hl2dm_bravo
      && chown ${nginx_u}:${gmod_alpha_g} /mnt/nginx_fastdl/gmod_alpha
      && chown ${nginx_u}:${gmod_bravo_g} /mnt/nginx_fastdl/gmod_bravo
      && chown ${nginx_u}:${gmod_charlie_g} /mnt/nginx_fastdl/gmod_charlie
      && chmod 2771 /mnt/nginx_fastdl/synergy
      && chmod 2771 /mnt/nginx_fastdl/hl2dm_alpha
      && chmod 2771 /mnt/nginx_fastdl/hl2dm_bravo
      && chmod 2771 /mnt/nginx_fastdl/gmod_alpha
      && chmod 2771 /mnt/nginx_fastdl/gmod_bravo
      && chmod 2771 /mnt/nginx_fastdl/gmod_charlie
      && chown -R root:${admin_g} /mnt/nginx_conf/
      && chmod -R 775 /mnt/nginx_conf/
      && setfacl -d -m u::rwx,g::rwx,o::- /mnt/nginx_websites
      && setfacl -d -m u::rwx,g::rwx,o::- /mnt/nginx_fastdl"
    cap_drop:
      - ALL 
    cap_add:
      - CAP_DAC_OVERRIDE
      - CAP_CHOWN
      - CAP_FOWNER
      - CAP_FSETID
    network_mode: none
    depends_on: 
      nginx_links:
        condition: service_completed_successfully
    <<: [*labels]
  #restart: on-failure
  # Production nginx, for use only on a machine the real domain is pointing to.
  nginx_envsubst_conf_production:
    <<: [*nginx_envsubst_conf, *nginx_envsubst_production]
  nginx_envsubst_snippets_production:
    <<: [*nginx_envsubst_snippets, *nginx_envsubst_production]
  nginx_production: 
    <<: [ *nginx ]
    profiles:
      - production
    networks:
      <<: [ *nginx_networks ]
      portainer:
    extra_hosts:
      - "searxng:172.50.10.1"
      - "portainer:172.60.10.1"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/configs/users/passwd:/etc/passwd:ro
      - ./data/configs/users/group:/etc/group:ro
      - ./data/configs/users/shadow:/etc/shadow:ro 
      - ./data/configs/users/gshadow:/etc/gshadow:ro
      - ${MOUNT_PROC_CPUINFO}:/proc/cpuinfo:rw
      - ${MOUNT_PROC_MEMINFO}:/proc/meminfo:rw
      - ${MOUNT_PROC_SWAPS}:/proc/swaps:rw
      - ${MOUNT_PROC_STAT}:/proc/stat:rw
      - ${MOUNT_PROC_DISKSTATS}:/proc/diskstats:rw
      - ${MOUNT_PROC_UPTIME}:/proc/uptime:rw
      - ${MOUNT_PROC_SLABINFO}:/proc/slabinfo:rw
      - ${MOUNT_SYS_DEVICES_SYSTEM_CPU}:/sys/devices/system/cpu:rw
      - php_fpm_run:/var/run/php-fpm
      - nginx_cache:/mnt/cache
      - nginx_websites:/mnt/websites
      - nginx_fastdl:/mnt/fastdl
      - phpmyadmin:/mnt/admin/phpmyadmin
      - svencoop_shared:/mnt/links/svencoop_shared:ro
      - ./data/configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/configs/nginx/snippets:/etc/nginx/snippets:ro
      - ./data/configs/nginx/conf.d:/etc/nginx/conf.d:ro
      - dhparam:/etc/dhparam:ro
      - certbot_conf:/etc/letsencrypt:ro
      - certbot_www:/var/www/certbot:ro
    environment:
      <<: [ *nginx_envsubst_production_environment ]
    depends_on:
      <<: [ *nginx_dependencies ]
      certbot:
        condition: service_healthy
      nginx_envsubst_conf_production:
        condition: service_completed_successfully 
      nginx_envsubst_snippets_production:
        condition: service_completed_successfully
      nginx_permissions:
        condition: service_completed_successfully
      php_fpm_production:
        condition: service_started
  # Development nginx (because Let's Encrypt only works on the actual domain)
  nginx_envsubst_conf_development:
    <<: [ *nginx_envsubst_conf, *nginx_envsubst_development ]
  nginx_envsubst_snippets_development:
    <<: [ *nginx_envsubst_snippets, *nginx_envsubst_development ]
  nginx_development:
    <<: [ *nginx ]
    profiles:
      - development
    networks:
      <<: [ *nginx_networks ]
      portainer:
    volumes:    
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/configs/users/passwd:/etc/passwd:ro
      - ./data/configs/users/group:/etc/group:ro
      - ./data/configs/users/shadow:/etc/shadow:ro 
      - ./data/configs/users/gshadow:/etc/gshadow:ro
      - ${MOUNT_PROC_CPUINFO}:/proc/cpuinfo:rw
      - ${MOUNT_PROC_MEMINFO}:/proc/meminfo:rw
      - ${MOUNT_PROC_SWAPS}:/proc/swaps:rw
      - ${MOUNT_PROC_STAT}:/proc/stat:rw
      - ${MOUNT_PROC_DISKSTATS}:/proc/diskstats:rw
      - ${MOUNT_PROC_UPTIME}:/proc/uptime:rw
      - ${MOUNT_PROC_SLABINFO}:/proc/slabinfo:rw
      - ${MOUNT_SYS_DEVICES_SYSTEM_CPU}:/sys/devices/system/cpu:rw
      - php_fpm_run:/var/run/php-fpm
      - nginx_cache:/mnt/cache
      - nginx_websites:/mnt/websites
      - nginx_fastdl:/mnt/fastdl
      - phpmyadmin:/mnt/admin/phpmyadmin
      - svencoop_shared:/mnt/links/svencoop_shared:ro
      - ./data/configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/configs/nginx/snippets:/etc/nginx/snippets:ro
      - ./data/configs/nginx/conf.d:/etc/nginx/conf.d:ro
      - dhparam:/etc/dhparam:ro
      - mkcert:/etc/mkcert:ro
    environment:
      <<: [ *nginx_envsubst_development_environment ]
    depends_on:
      <<: [ *nginx_dependencies ]
      mkcert:
        condition: service_healthy
      nginx_envsubst_conf_development:
        condition: service_completed_successfully 
      nginx_envsubst_snippets_development:
        condition: service_completed_successfully
      nginx_permissions:
        condition: service_completed_successfully
      php_fpm_development:
        condition: service_started

volumes:
  nginx_cache:
  nginx_websites:
  nginx_fastdl:
  phpmyadmin:
  svencoop:
networks:
  nginx:
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/23
  searxng:
    ipam:
      driver: default 
      config:
        - subnet: 172.50.10.0/22
  portainer:
    ipam:
      driver: default 
      config:
        - subnet: 172.60.10.0/22
