version: "3.9"
services:
  nginx:
    user: "${NGINX_UID}:${NZC_GID}"
    build:
      context: ./build/nginx/
      args:
        UID: ${NGINX_UID}
        GID: ${NGINX_GID} 
    volumes:
      - svencoop:/usr/share/nginx/svencoop
    ports:
      - ${NGINX_PORT}:8080
volumes:
  nginx:
