version: "3.9"
x-nginx: &nginx
  build:
    context: ./build/nginx
    args:
      UID: ${nginx_u}
      GID: ${nginx_g}
  user: "${nginx_u}:${nginx_g}"
  group_add:
    - ${gmod_g}
    - ${svencoop_g}
  networks:
    - nginx
    - searxng
  ports:
    - ${NGINX_HTTP_PORT:-80}:80
    - ${NGINX_HTTPS_PORT:-443}:443
  extra_hosts:
    - "searxng:172.50.10.1"
  healthcheck:
    test: "curl -f http://${DOMAIN_NAME} || exit 1"
    start_period: 5s
    interval: 10s
    timeout: 10s
    retries: 3
  environment:
    - DOMAIN_NAME=${DOMAIN_NAME}
  cpuset: ${NGINX_CPU}
  cpu_shares: 2048
  deploy:
    resources:
      limits:
        memory: 1024M
      reservations:
        memory: 512M
  blkio_config:
    weight: 800
    device_write_bps:
      - path: ${DISK}
        rate: 50000000
    device_read_bps:
      - path: ${DISK}
        rate: 50000000
    device_read_iops:
      - path: ${DISK}
        rate: 100
    device_write_iops:
      - path: ${DISK}
        rate: 100
  restart: unless-stopped
x-nginx_envsubst_conf: &nginx_envsubst_conf
  build:
    context: ./build/nginx_envsubst
  volumes:
    - ./data/nginx/conf.d.template:/mnt/input
    - ./data/nginx/conf.d:/mnt/output
  network_mode: none
  cap_drop:
    - ALL
x-nginx_envsubst_snippets: &nginx_envsubst_snippets
  build:
    context: ./build/nginx_envsubst
  volumes:
    - ./data/nginx/snippets.template:/mnt/input
    - ./data/nginx/snippets:/mnt/output
  network_mode: none
  cap_drop:
    - ALL
x-nginx_envsubst_production: &nginx_envsubst_production
  profiles:
    - production
  environment:  
    - DOMAIN_NAME=${DOMAIN_NAME}
    - WEBSITES_ROOT="/mnt/websites"
    - FASTDL_ROOT="/mnt/fastdl"
    - NGINX_SSL_CERT="/etc/letsencrypt/live/chronicles.local/cert.pem"
    - NGINX_SSL_CERT_KEY="/etc/letsencrypt/live/chronicles.local/privkey.pem"
    - NGINX_SSL_DHPARAM="/etc/letsencrypt/ssl-dhparams.pem" 
x-nginx_envsubst_development: &nginx_envsubst_development
  profiles:
    - development
  environment:
    - DOMAIN_NAME=${DOMAIN_NAME}
    - WEBSITES_ROOT="/mnt/websites"
    - FASTDL_ROOT="/mnt/fastdl"
    - NGINX_SSL_CERT="/etc/mkcert/mkcert.pem"
    - NGINX_SSL_CERT_KEY="/etc/mkcert/mkcert.key"
    - NGINX_SSL_DHPARAM="/etc/mkcert/mkcert.dh"
services:
  nginx_links:
    image: alpine:3.17.2
    volumes:
      - nginx_fastdl:/mnt/fastdl
    command: >
      /bin/sh -c "mkdir -p /mnt/links/svencoop/svencoop
      && rm /mnt/fastdl/svencoop
      && ln -sf /mnt/links/svencoop/svencoop /mnt/fastdl/svencoop"
    cap_drop:
      - ALL 
    cap_add:
      - CAP_DAC_OVERRIDE
    network_mode: none
    restart: on-failure
  nginx_permissions:
    image: alpine:3.17.2
    volumes: 
      - ./data/users/passwd:/etc/passwd:ro
      - ./data/users/group:/etc/group:ro
      - ./data/users/shadow:/etc/shadow:ro
      - ./data/users/gshadow:/etc/gshadow:ro
      - nginx_websites:/mnt/nginx_websites
      - nginx_fastdl:/mnt/nginx_fastdl
      - ./data/nginx/cpu:/mnt/nginx_cpu
      - ./data/nginx:/mnt/nginx_conf
      - mkcert:/mnt/mkcert
      - certbot_conf:/mnt/certbot_conf
      - certbot_www:/mnt/certbot_www
    command: >
      /bin/sh -c "echo \"${NGINX_CPU}\" > /mnt/nginx_cpu/online
      && chown ${nginx_u}:${websites_g} 
      /mnt/nginx_websites 
      /mnt/nginx_fastdl
      && chmod 3770 
      /mnt/nginx_websites 
      /mnt/nginx_fastdl
      && chown -R root:${admin_g} /mnt/nginx_conf/
      && chmod -R 775 /mnt/nginx_conf/
      && chown -fR ${nginx_u}:root /mnt/mkcert/
      && if [ -f '/mnt/certbot_conf/ssl-dhparams.pem' ]; then
        chown -f nginx:${admin_g} /mnt/certbot_conf/ssl-dhparams.pem
      fi
      && if [ -d '/mnt/certbot_conf/live/' ]; then
        chown -fR nginx:${admin_g} /mnt/certbot_conf/live/
      fi"
    network_mode: none
    cap_drop:
      - ALL 
    cap_add:
      - CHOWN
      - CAP_FOWNER
    depends_on: 
      nginx_links:
        condition: service_completed_successfully
      certbot:
        condition: service_started
      mkcert:
        condition: service_completed_successfully
      openssl:
        condition: service_completed_successfully
    restart: on-failure
  # Production nginx, for use only on a machine the real domain is pointing to.
  certbot:
    image: certbot/certbot:v2.3.0
    profiles:
      - production
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    networks:
      - nginx
    restart: unless-stopped       
  nginx_envsubst_conf_production:
    <<: *nginx_envsubst_conf
    profiles:
      - production 
  nginx_envsubst_conf_production:
    <<: *nginx_envsubst_conf
    <<: *nginx_envsubst_production
  nginx_envsubst_snippets_production:
    <<: *nginx_envsubst_snippets
    <<: *nginx_envsubst_production
  nginx_production: 
    <<: *nginx  
    profiles:
      - production
    volumes:
      - ./data/users/passwd:/etc/passwd:ro
      - ./data/users/group:/etc/group:ro
      - ./data/users/shadow:/etc/shadow:ro 
      - ./data/users/gshadow:/etc/gshadow:ro
      - ./data/nginx/cpu/online:/sys/devices/system/cpu/online:ro
      - nginx_websites:/mnt/websites
      - nginx_fastdl:/mnt/fastdl
      - svencoop:/mnt/links/svencoop:ro
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/nginx/snippets:/etc/nginx/snippets:ro
      - ./data/nginx/conf.d:/etc/nginx/conf.d:ro
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    depends_on:
      nginx_envsubst_conf_production:
        condition: service_completed_successfully 
      nginx_envsubst_snippets_production:
        condition: service_completed_successfully
      nginx_permissions:
        condition: service_completed_successfully
  # Development nginx (because Let's Encrypt only works on the actual domain)
  mkcert:
    image: ethorbit/mkcert:latest
    profiles:
      - development
    volumes:
      - ${CA_TRUST_STORE_DIR:-/usr/local/share/ca-certificates}:/usr/local/share/ca-certificates
      - mkcert:/mnt
    command: > 
      /bin/sh -c "[[ ! -s /mnt/mkcert.pem || ! -s /mnt/mkcert.key ]]
      && mkcert -install
      && mkcert -cert-file /mnt/mkcert.pem -key-file /mnt/mkcert.key
      *.${DOMAIN_NAME} 
      || exit 0" 
    network_mode: none 
  openssl:
    image: ethorbit/openssl:latest
    profiles:
      - development
    volumes:
      - mkcert:/mnt
    command: >
      /bin/sh -c "[[ ! -s /mnt/mkcert.dh ]]
      && openssl dhparam -out /mnt/mkcert.dh 2048
      || exit 0"
  nginx_dnsmasq:
    image: ethorbit/dnsmasq:latest
    profiles:
      - development
    volumes:
      - ./data/nginx/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
    ports:
      - 53/udp
    networks:
      nginx:
        ipv4_address: 172.10.1.1
    depends_on:
      nginx_envsubst_dnsmasq_development:
        condition: service_completed_successfully
  nginx_envsubst_conf_development:
    <<: *nginx_envsubst_conf
    <<: *nginx_envsubst_development
  nginx_envsubst_snippets_development:
    <<: *nginx_envsubst_snippets
    <<: *nginx_envsubst_development
  nginx_envsubst_dnsmasq_development:
    image: ethorbit/envsubst:latest
    volumes:
      - ./data/nginx/dnsmasq:/mnt
    command: >
      /bin/sh -c "envsubst `printf '$${%s}\n' DOMAIN_NAME` 
      < /mnt/dnsmasq.conf.template > /mnt/dnsmasq.conf"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    network_mode: none
    cap_drop:
      - ALL
  nginx_development:
    <<: *nginx
    profiles:
      - development
    volumes:    
      - ./data/users/passwd:/etc/passwd:ro
      - ./data/users/group:/etc/group:ro
      - ./data/users/shadow:/etc/shadow:ro 
      - ./data/users/gshadow:/etc/gshadow:ro
      - ./data/nginx/cpu/online:/sys/devices/system/cpu/online:ro
      - nginx_websites:/mnt/websites
      - nginx_fastdl:/mnt/fastdl
      - svencoop:/mnt/links/svencoop:ro
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/nginx/snippets:/etc/nginx/snippets:ro
      - ./data/nginx/conf.d:/etc/nginx/conf.d:ro
      - mkcert:/etc/mkcert
    dns:
      - 172.10.1.1
    depends_on:
      nginx_envsubst_conf_development:
        condition: service_completed_successfully 
      nginx_envsubst_snippets_development:
        condition: service_completed_successfully
      nginx_permissions:
        condition: service_completed_successfully
      nginx_dnsmasq:
        condition: service_started
volumes:
  nginx_websites:
  nginx_fastdl:
  certbot_conf:
  certbot_www:
  mkcert:
networks:
  nginx:
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/23
  searxng:
    ipam:
      driver: default 
      config:
        - subnet: 172.50.10.0/22
