version: "3.9"
x-php_fpm: &php_fpm
  #container_name: ${CONTAINER_NAME_PREFIX}-php_fpm-${CONTAINER_NAME_SUFFIX}
  networks:
    php:
      ipv4_address: 172.119.1.1
    mysql:
    nginx:
    gmod:
    svencoop:
  # This should allow PHP scripts to do things like display game server stats and whatnot
  #   External network -> Public IP:Port #
  #   Internal network -> gameserver container's IP:Port #
  extra_hosts:
    - "${DOMAIN_NAME}:172.10.1.2"
    - "${WEBSITE_SUBDOMAIN}.${DOMAIN_NAME}:172.10.1.2"
    - "${FASTDL_SUBDOMAIN}.${DOMAIN_NAME}:172.10.1.2"
    - "gmod-1.${DOMAIN_NAME}:172.150.1.1"
    - "gmod-2.${DOMAIN_NAME}:172.150.1.2"
    - "gmod-3.${DOMAIN_NAME}:172.150.1.3"
    - "svencoop.${DOMAIN_NAME}:172.151.1.1"
  hostname: php_fpm
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./data/configs/users/passwd:/etc/passwd:ro
    - ./data/configs/users/group:/etc/group:ro
    - ./data/configs/users/shadow:/etc/shadow:ro 
    - ./data/configs/users/gshadow:/etc/gshadow:ro
    - ./data/configs/nginx/cpu/online:/sys/devices/system/cpu/online:ro
    - ./data/configs/php_fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
    - php_fpm_run:/var/run/php-fpm
    - nginx_websites:/mnt/websites
    - phpmyadmin:/mnt/admin/phpmyadmin
  command: >
    /bin/sh -c "rm /var/run/php-fpm/sock 2> /dev/null
    ; touch /var/run/php-fpm/sock
    && chown ${php_u}:${php_g} /var/run/php-fpm
    && chmod 770 /var/run/php-fpm
    && chown ${php_u}:${php_g} /var/run/php-fpm/sock
    && chmod 770 /var/run/php-fpm/sock
    && php-fpm"
  cpuset: ${NGINX_CPU} # Since we handle the workloads of php (which is closely tied to webserver), we might as well use the same cores..
  cpu_shares: 2048
  # Website PHP scripts are actually logged to nginx, this only logs the php-fpm process itself (so kinda useless)
  depends_on:
    rsyslog:
      condition: service_healthy
  logging:
    driver: syslog
    options:
      mode: non-blocking
      syslog-address: "tcp://localhost:${RSYSLOG_PORT}"
      tag: "php_fpm"
  restart: always
services:
  php_fpm_development:
    <<: [ *php_fpm ]
    profiles: 
      - development 
    build:
      target: development
      context:
        ./build/php_fpm
      args:
        - UID=${php_u}
        - GID=${php_g}
  php_fpm_production:
    <<: [ *php_fpm ]
    profiles: 
      - production
    build:
      target: production
      context:
        ./build/php_fpm
      args:
        - UID=${php_u}
        - GID=${php_g}
volumes:
  php_fpm_run:
networks:
  php:
    ipam:
      driver: default 
      config:
        - subnet: 172.119.1.0/22
