version: "3.9"
services:
  phpmyadmin_envsubst:
    build:
      context: ./build/input_output_envsubst
      args:
        FILE_EXTENSION: "php"
    environment:
      - PHPMYADMIN_BLOWFISH_SECRET=${PHPMYADMIN_BLOWFISH_SECRET}
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=${ADMIN_PASSWORD}
      - PMA_HOST=mysql
    volumes:
      - ./data/configs/phpmyadmin/template:/mnt/input
      - ./data/configs/phpmyadmin:/mnt/output
    network_mode: none
    cap_drop:
      - ALL
    cap_add:
      - CAP_DAC_OVERRIDE
      - CAP_FOWNER
    restart: on-failure
  phpmyadmin_permissions:
    build:
      context: ./build/permissions
    volumes:
      - ./data/configs/phpmyadmin:/mnt
    command: >
      /bin/sh -c 'chown ${phpmyadmin_u}:${php_g} /mnt/config.inc.php
      && chmod 760 /mnt/config.inc.php'
    cap_drop:
      - ALL
    cap_add:
      - CAP_DAC_OVERRIDE
      - CAP_CHOWN
      - CAP_FOWNER
      - CAP_FSETID
    network_mode: none
    restart: on-failure
  phpmyadmin:
    build:
      context: ./build/phpmyadmin
      args:
        UID: ${phpmyadmin_u}
        GID: ${websites_g}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/configs/phpmyadmin/config.inc.php:/var/www/html/config.inc.php
      - phpmyadmin:/panel
    depends_on:
      phpmyadmin_envsubst:
        condition:
          service_completed_successfully
      phpmyadmin_permissions:
        condition:
          service_completed_successfully
    network_mode: none 
    restart: on-failure
volumes:
  phpmyadmin:
