version: "3.9"
services:
  phpmyadmin:
    build:
      context: ./build/phpmyadmin
      args:
        UID: ${phpmyadmin_u}
        GID: ${websites_g}
    #environment:
      #- MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      #- MYSQL_USER=admin
      #- MYSQL_PASSWORD=${MYSQL_REMOTE_PASSWORD}
      #- PMA_HOST=mysql
      #networks:
      #- mysql
      #- phpmyadmin  
    network_mode: none 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - phpmyadmin:/panel
    #ports:
      #- 8085:80 
    restart: unless-stopped
volumes:
  phpmyadmin:
