version: "3.9"
services:
  portainer:
    image: portainer/portainer-ce:latest
    networks:
      portainer:
        ipv4_address: 172.60.10.1
      nginx:
    ports:
      - ${PORTAINER_PORT:-5059}:9000/tcp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
    cpuset: ${PORTAINER_CPU}
    cpu_shares: 60
    deploy:
      resources:
        limits:
          memory: 312M 
        reservations:
          memory: 250M
    restart: unless-stopped
