version: "3.9"
services:
  rsyslog_envsubst:
    build:
      context: ./build/input_output_envsubst
      args:
        FILE_EXTENSION: "conf"
    environment:
      - RSYSLOG_PORT=${RSYSLOG_PORT}
    volumes:
      - ./data/configs/rsyslog/template:/mnt/input
      - ./data/configs/rsyslog:/mnt/output
    network_mode: none
    cap_drop:
      - ALL
    cap_add:
      - CAP_DAC_OVERRIDE
      - CAP_FOWNER
    restart: on-failure
  rsyslog:
    build:
      context: ./build/rsyslog
      args:
        - UID=${rsyslog_u}
        - GID=${rsyslog_g}
    command: '-n'
    tty: true
    stdin_open: true
    ports:
      - ${RSYSLOG_PORT}:514/tcp
    #networks:
    #  - rsyslog
    #network_mode: host
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/configs/rsyslog/rsyslog.conf:/etc/rsyslog.conf
      - rsyslog_logs:/logs
    depends_on:
      rsyslog_envsubst:
        condition: service_completed_successfully
    restart: always
volumes:
  rsyslog_logs:
#networks:
#rsyslog:
