# This is just here temporarily so the project can still run
# Each service is eventually going to have its own dedicated rsyslog service 
# for fine-grained permissions
version: "3.9"
services:
  rsyslog:
    build:
      context: ./build/rsyslog
      args:
        - UID=${rsyslog_u}
        - GID=${staff_g}
        - PORT=${RSYSLOG_PORT}
    command: '-n'
    tty: true
    stdin_open: true
    hostname: rsyslog
    ports:
      - 127.0.0.1:${RSYSLOG_PORT}:${RSYSLOG_PORT}/tcp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/configs/rsyslog/rsyslog.conf:/etc/rsyslog.conf
      - rsyslog_logs:/logs
    healthcheck:
      test: "/healthcheck.sh"
      start_period: 5s
      interval: 5s
      timeout: 10s
      retries: 3
    restart: always
volumes:
  rsyslog_logs:
