version: "3.9"
x-cpu-limits: &cpu-limits
  cpuset: ${SEARXNG_CPU}
  cpu_shares: 20
x-io-limits: &io-limits 
  blkio_config:
    weight: 25
    device_write_bps:
      - path: ${DISK}
        rate: 10000000
    device_read_bps:
      - path: ${DISK}
        rate: 10000000
    device_read_iops:
      - path: ${DISK}
        rate: 50
    device_write_iops:
      - path: ${DISK}
        rate: 50  
services:
  redis:
    image: redis:6-alpine
    command: redis-server --save "" --appendonly "no"
    networks:
      - searxng
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    <<: [ *cpu-limits, *io-limits ]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M
  searxng:
    image: searxng/searxng:2023.4.25-216751da
    networks:
      searxng:
        ipv4_address: 172.50.10.1
      nginx:
    ports:
      - "8080:8080"
    volumes:
      - ./data/configs/searxng:/etc/searxng:rw
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "none"
    <<: [ *cpu-limits, *io-limits ]
    deploy:
      resources:
        limits:
          memory: 156M 
        reservations:
          memory: 128M
    restart: unless-stopped
