version: "3.9"
x-cpu-limits: &cpu-limits
  cpuset: ${SEARXNG_CPU}
  cpu_shares: 20
x-io-limits: &io-limits 
  blkio_config:
    weight: 25
    device_write_bps:
      - path: ${DISK}
        rate: '10m'
    device_read_bps:
      - path: ${DISK}
        rate: '10m'
    device_read_iops:
      - path: ${DISK}
        rate: 95
    device_write_iops:
      - path: ${DISK}
        rate: 95
services:
  redis:
    profiles:
      - optional
    image: redis:6-alpine
    command: redis-server --save "" --appendonly "no"
    networks:
      searxng:
        ipv4_address: 172.50.10.2
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    ports:
      - 127.0.0.1:${REDIS_PORT:-6379}:6379/tcp
    <<: [ *cpu-limits, *io-limits ]
    volumes:
      - ${MOUNT_PROC_CPUINFO}:/proc/cpuinfo:rw
      - ${MOUNT_PROC_MEMINFO}:/proc/meminfo:rw
      - ${MOUNT_PROC_SWAPS}:/proc/swaps:rw
      - ${MOUNT_PROC_STAT}:/proc/stat:rw
      - ${MOUNT_PROC_DISKSTATS}:/proc/diskstats:rw
      - ${MOUNT_PROC_UPTIME}:/proc/uptime:rw
      - ${MOUNT_PROC_SLABINFO}:/proc/slabinfo:rw
      - ${MOUNT_SYS_DEVICES_SYSTEM_CPU}:/sys/devices/system/cpu:rw
    restart: always
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M
    logging:
      driver: "none"
  searxng_envsubst:
    profiles:
      - optional
    build:
      context: ./build/input_output_envsubst
      args:
        FILE_EXTENSION: "yml"
    environment:
      - REDIS_PORT=${REDIS_PORT}
      - SEARXNG_SECRET_KEY=${SEARXNG_SECRET_KEY}
    volumes:
      - ./data/configs/searxng/template:/mnt/input
      - ./data/configs/searxng:/mnt/output
    network_mode: none
    cap_drop:
      - ALL
    cap_add:
      - CAP_DAC_OVERRIDE
      - CAP_FOWNER
    restart: on-failure
  searxng:
    profiles:
      - optional
    image: searxng/searxng:2023.4.25-216751da
    networks:
      searxng:
        ipv4_address: 172.50.10.1
      nginx:
    hostname: searxng
    extra_hosts:
      - "redis:172.50.10.2"
    ports:
      - 127.0.0.1:${SEARXNG_PORT:-8080}:8080/tcp
    volumes:
      - ${MOUNT_PROC_CPUINFO}:/proc/cpuinfo:rw
      - ${MOUNT_PROC_MEMINFO}:/proc/meminfo:rw
      - ${MOUNT_PROC_SWAPS}:/proc/swaps:rw
      - ${MOUNT_PROC_STAT}:/proc/stat:rw
      - ${MOUNT_PROC_DISKSTATS}:/proc/diskstats:rw
      - ${MOUNT_PROC_UPTIME}:/proc/uptime:rw
      - ${MOUNT_PROC_SLABINFO}:/proc/slabinfo:rw
      - ${MOUNT_SYS_DEVICES_SYSTEM_CPU}:/sys/devices/system/cpu:rw
      - ./data/configs/searxng:/etc/searxng:rw
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "none"
    <<: [ *cpu-limits, *io-limits ]
    deploy:
      resources:
        limits:
          memory: 156M 
        reservations:
          memory: 128M
    depends_on:
      searxng_envsubst:
        condition: service_completed_successfully
      redis:
        condition: service_started
    restart: always
