version: "3.9"
x-cpu-limits: &cpu-limits
  cpuset: ${SEARXNG_CPU}
  cpu_shares: 20
x-io-limits: &io-limits 
  blkio_config:
    weight: 25
    device_write_bps:
      - path: ${DISK}
        rate: 10000000
    device_read_bps:
      - path: ${DISK}
        rate: 10000000
    device_read_iops:
      - path: ${DISK}
        rate: 50
    device_write_iops:
      - path: ${DISK}
        rate: 50  
services:
  redis:
    image: redis:6-alpine
    command: redis-server --save "" --appendonly "no"
    #networks:
    #- searxng
    network_mode: host
    tmpfs:
      - /var/lib/redis
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    ports:
      - 127.0.0.1:${REDIS_PORT:-6379}:6379/tcp
    <<: [ *cpu-limits, *io-limits ]
    restart: always
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 32M
    logging:
      driver: "none"
  searxng_envsubst:
    build:
      context: ./build/input_output_envsubst
      args:
        FILE_EXTENSION: "yml"
    environment:
      - REDIS_PORT=${REDIS_PORT}
      - SEARXNG_SECRET_KEY=${SEARXNG_SECRET_KEY}
    volumes:
      - ./data/configs/searxng/template:/mnt/input
      - ./data/configs/searxng:/mnt/output
    network_mode: none
    cap_drop:
      - ALL
    cap_add:
      - CAP_DAC_OVERRIDE
      - CAP_FOWNER
    restart: on-failure
  searxng:
    image: searxng/searxng:2023.4.25-216751da
    #networks:
      #searxng:
      #ipv4_address: 172.50.10.1
      #nginx:
      #ports:
      #- "8080:8080"
    hostname: searxng
    network_mode: host
    ports:
      - 127.0.0.1:${SEARXNG_PORT:-8080}:8080/tcp
    volumes:
      - ./data/configs/searxng:/etc/searxng:rw
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "none"
    <<: [ *cpu-limits, *io-limits ]
    deploy:
      resources:
        limits:
          memory: 156M 
        reservations:
          memory: 128M
    depends_on:
      searxng_envsubst:
        condition: service_completed_successfully
      redis:
        condition: service_started
    restart: always
