version: "3.9"
services:
  sshd_permissions: 
    build:
      context: ./build/permissions
    volumes:
      - sftp:/mnt
    command: >
      /bin/sh -c 'for d in game_servers discord_bots admin_websites; do 
      mkdir -p "/mnt/$$d" 
      chown root:root "/mnt/$$d" 
      chmod 751 "/mnt/$$d"; 
      done
      && for d in admin_websites/phpmyadmin admin_websites/portainer; do 
      mkdir -p "/mnt/$$d" 
      chmod 750 "/mnt/$$d"; 
      done
      && for d in discord_bots/stickies; do 
      mkdir -p "/mnt/$$d" 
      chown root:root "/mnt/$$d" 
      chmod 750 "/mnt/$$d"; 
      done
      && mkdir -p /mnt/game_servers/gmod/alpha /mnt/game_servers/gmod/bravo /mnt/game_servers/gmod/charlie
      && mkdir -p /mnt/game_servers/hl2dm/alpha /mnt/game_servers/hl2dm/bravo
      && mkdir -p /mnt/game_servers/svencoop/shared /mnt/game_servers/svencoop/1 /mnt/game_servers/svencoop/2
      && mkdir -p /mnt/game_servers/synergy
      && mkdir -p /mnt/game_servers/ark/shared /mnt/game_servers/ark/1'
    cap_drop:
      - ALL 
    cap_add:
      - CAP_DAC_OVERRIDE
      - CAP_CHOWN
      - CAP_FOWNER
      - CAP_FSETID
    network_mode: none
    restart: on-failure
  sshd_envsubst:
    image: ethorbit/envsubst:latest
    volumes:
      - ./data/configs/ssh:/mnt
    command: >
      /bin/sh -c "envsubst `printf '$${%s}\n' SSH_PORT` 
      < /mnt/sshd_config.template > /mnt/sshd_config"
    environment:
      - SSH_PORT=${SSH_PORT}
    network_mode: none
    restart: on-failure
  sshd:
    build:
      context: ./build/sshd
    networks:
      - ssh
    ports:
      - ${SSH_PORT:-22}:${SSH_PORT:-22}
    hostname: sshd
    logging:
      driver: syslog
      options:
        mode: non-blocking
        syslog-address: "tcp://localhost:${RSYSLOG_PORT}"
        tag: "sshd"
    volumes:
      - home:/home
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/configs/users/passwd:/etc/passwd:ro
      - ./data/configs/users/group:/etc/group:ro
      - ./data/configs/users/shadow:/etc/shadow:ro
      - ./data/configs/users/gshadow:/etc/gshadow:ro
      - ${MOUNT_PROC_CPUINFO}:/proc/cpuinfo:rw
      - ${MOUNT_PROC_MEMINFO}:/proc/meminfo:rw
      - ${MOUNT_PROC_SWAPS}:/proc/swaps:rw
      - ${MOUNT_PROC_STAT}:/proc/stat:rw
      - ${MOUNT_PROC_DISKSTATS}:/proc/diskstats:rw
      - ${MOUNT_PROC_UPTIME}:/proc/uptime:rw
      - ${MOUNT_PROC_SLABINFO}:/proc/slabinfo:rw
      - ${MOUNT_SYS_DEVICES_SYSTEM_CPU}:/sys/devices/system/cpu:rw
      - ./data/configs/ssh/sshd_config:/etc/ssh/sshd_config
      - sftp:/mnt
      - mysql_backups:/mnt/mysql_backups
      - svencoop_shared:/mnt/game_servers/svencoop/shared
      - svencoop_1:/mnt/game_servers/svencoop/1
      - svencoop_2:/mnt/game_servers/svencoop/2
      - synergy:/mnt/game_servers/synergy
      - hl2dm_alpha_shared:/mnt/game_servers/hl2dm/alpha/shared
      - hl2dm_bravo_shared:/mnt/game_servers/hl2dm/bravo/shared
      - hl2dm_alpha_1:/mnt/game_servers/hl2dm/alpha/1
      - hl2dm_bravo_1:/mnt/game_servers/hl2dm/bravo/1
      - gmod_alpha_shared:/mnt/game_servers/gmod/alpha/shared
      - gmod_bravo_shared:/mnt/game_servers/gmod/bravo/shared
      - gmod_charlie_shared:/mnt/game_servers/gmod/charlie/shared
      - gmod_alpha_1:/mnt/game_servers/gmod/alpha/1
      - gmod_alpha_2:/mnt/game_servers/gmod/alpha/2
      - gmod_alpha_3:/mnt/game_servers/gmod/alpha/3
      - gmod_bravo_1:/mnt/game_servers/gmod/bravo/1
      - gmod_charlie_1:/mnt/game_servers/gmod/charlie/1
      - ark_1:/mnt/game_servers/ark/1
      - ark_shared:/mnt/game_servers/ark/shared
      - nginx_fastdl:/mnt/fastdl
      - nginx_websites:/mnt/websites
      - discord_sticky_bot:/mnt/discord_bots/stickies
      - phpmyadmin:/mnt/admin_websites/phpmyadmin
      - portainer_data:/mnt/admin_websites/portainer
      - rsyslog_logs:/mnt/logs
    depends_on:
      sshd_permissions:
        condition:
          service_completed_successfully
      sshd_envsubst:
        condition: 
          service_completed_successfully
      rsyslog:
        condition: service_healthy
    cpuset: ${SSH_CPU}
    cpu_shares: 256
    deploy:
      resources:
        limits:
          memory: ${SSH_RAM:-352M}
        reservations:
          memory: 128M  
    blkio_config:
      weight: 450
      device_write_bps:
        - path: ${DISK}
          rate: '80m'
      device_read_bps:
        - path: ${DISK}
          rate: '100m'
      device_read_iops:
        - path: ${DISK}
          rate: 300
      device_write_iops:
        - path: ${DISK}
          rate: 220
    restart: always

networks:
  ssh:
volumes:
  sftp:
  rsyslog_logs:
  mysql_backups:
  nginx_websites:
  nginx_fastdl:
  phpmyadmin:
  portainer_data:
  discord_sticky_bot:
  svencoop_shared:
  svencoop_1:
  svencoop_2:
  synergy:
  hl2dm_alpha_shared:
  hl2dm_bravo_shared:
  hl2dm_alpha_1:
  hl2dm_bravo_1:
  gmod_alpha_shared:
  gmod_bravo_shared:
  gmod_charlie_shared:
  gmod_alpha_1:
  gmod_alpha_2:
  gmod_alpha_3:
  gmod_bravo_1:
  gmod_charlie_1:
  ark_1:
  ark_shared:
  home:
