version: "3.9"
services:
  sshd_permissions: 
    build:
      context: ./build/permissions
    volumes:
      - sftp:/mnt
    command: >
      /bin/sh -c 'for d in game_servers discord_bots admin_websites; do 
      mkdir -p "/mnt/$$d" 
      chown root:root "/mnt/$$d" 
      chmod 751 "/mnt/$$d"; 
      done
      && for d in admin_websites/phpmyadmin admin_websites/portainer; do 
      mkdir -p "/mnt/$$d"
      chmod 750 "/mnt/$$d"
      done
      && for d in discord_bots/stickies; do 
      mkdir -p "/mnt/$$d" 
      chown root:root "/mnt/$$d" 
      chmod 750 "/mnt/$$d"; 
      done
      && mkdir -p /mnt/game_servers/svencoop
      && chown root:root /mnt/game_servers/svencoop
      && chmod 751 /mnt/game_servers/svencoop'
    cap_drop:
      - ALL 
    cap_add:
      - CAP_DAC_OVERRIDE
      - CAP_CHOWN
      - CAP_FOWNER
      - CAP_FSETID
    network_mode: none
    restart: on-failure
  sshd_envsubst:
    image: ethorbit/envsubst:latest
    volumes:
      - ./data/configs/ssh:/mnt
    command: >
      /bin/sh -c "envsubst `printf '$${%s}\n' SSH_PORT` 
      < /mnt/sshd_config.template > /mnt/sshd_config"
    environment:
      - SSH_PORT=${SSH_PORT}
    network_mode: none
    restart: on-failure
  sshd:
    build:
      context: ./build/sshd
    networks:
      - ssh
    ports:
      - ${SSH_PORT:-22}:${SSH_PORT:-22}
    volumes:
      - home:/home
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/configs/users/passwd:/etc/passwd:ro
      - ./data/configs/users/group:/etc/group:ro
      - ./data/configs/users/shadow:/etc/shadow:ro
      - ./data/configs/users/gshadow:/etc/gshadow:ro
      - ./data/configs/ssh/sshd_config:/etc/ssh/sshd_config
      - sftp:/mnt
      - svencoop:/mnt/game_servers/svencoop
      - gmod_shared:/mnt/game_servers/gmod/shared
      - gmod_1:/mnt/game_servers/gmod/1
      - gmod_2:/mnt/game_servers/gmod/2
      - gmod_3:/mnt/game_servers/gmod/3
      - nginx_fastdl:/mnt/fastdl
      - nginx_websites:/mnt/websites
      - discord_sticky_bot:/mnt/discord_bots/stickies
      - phpmyadmin:/mnt/admin_websites/phpmyadmin
      - portainer_data:/mnt/admin_websites/portainer
    depends_on:
      sshd_permissions:
        condition:
          service_completed_successfully
      sshd_envsubst:
        condition: 
          service_completed_successfully
    cpu_shares: 256
    deploy:
      resources:
        limits:
          memory: 352M 
        reservations:
          memory: 128M  
    blkio_config:
      weight: 450
      device_write_bps:
        - path: ${DISK}
          rate: 83886080
      device_read_bps:
        - path: ${DISK}
          rate: 104857600
      device_read_iops:
        - path: ${DISK}
          rate: 300
      device_write_iops:
        - path: ${DISK}
          rate: 220
    restart: unless-stopped
networks:
  ssh:
volumes:
  sftp:
  nginx_websites:
  nginx_fastdl:
  phpmyadmin:
  portainer_data:
  discord_sticky_bot:
  svencoop:
  gmod_1:
  gmod_2:
  gmod_3:
  gmod_shared:
  home:

