version: "3.9"
services:
  sshd_permissions: 
    image: alpine:3.17.2
    volumes:
      - sftp:/mnt
    command: >
      /bin/sh -c 'for d in 1 2 testing; do 
      mkdir -p "/mnt/game_servers/gmod/$d" 
      chmod 751 "/mnt/game_servers/gmod/$d"; 
      done
      && mkdir -p /mnt/game_servers/svencoop
      && chmod 751 /mnt/game_servers/svencoop'
    network_mode: none
    restart: on-failure
  sshd_envsubst:
    image: ethorbit/envsubst:latest
    volumes:
      - ./data/ssh:/mnt
    command: >
      /bin/sh -c "envsubst `printf '$${%s}\n' SSH_PORT` 
      < /mnt/sshd_config.template > /mnt/sshd_config"
    environment:
      - SSH_PORT=${SSH_PORT}
    network_mode: none
  sshd:
    build:
      context: ./build/sshd
    networks:
      - ssh
    ports:
      - ${SSH_PORT:-22}:${SSH_PORT:-22}
    volumes:
      - home:/home
      - pam:/etc/pam.d
      - ./data/users/passwd:/etc/passwd:ro
      - ./data/users/group:/etc/group:ro
      - ./data/users/shadow:/etc/shadow:ro
      - ./data/users/gshadow:/etc/gshadow:ro
      - ./data/ssh/sshd_config:/etc/ssh/sshd_config
      - sftp:/mnt
      - svencoop:/mnt/game_servers/svencoop
      - gmod_shared:/mnt/game_servers/gmod/shared
      - gmod_1:/mnt/game_servers/gmod/1
      - gmod_2:/mnt/game_servers/gmod/2
      - gmod_3:/mnt/game_servers/gmod/testing
    depends_on:
      sshd_permissions:
        condition:
          service_completed_successfully
      sshd_envsubst:
        condition: 
          service_completed_successfully
    restart: unless-stopped
networks:
  ssh:
volumes:
  svencoop:
  gmod_1:
  gmod_2:
  gmod_3:
  gmod_shared:
  sftp:
  home:
  pam:

