version: "3.9"

x-ssl-rsyslog: &ssl_rsyslog
  command: '-n'
  tty: true
  stdin_open: true
  healthcheck:
    test: "/healthcheck.sh"
    start_period: 5s
    interval: 5s
    timeout: 10s
    retries: 3
  restart: always
  
x-labels: &labels
  labels:
    - "io.portainer.accesscontrol.teams=websites"

x-healthcheck: &healthcheck
  healthcheck:
    test: /bin/sh -c '/healthcheck.sh || exit 1' 
    interval: 15s
    timeout: 8s
    retries: 2
    start_period: 15s

services:
  # I don't think it's even possible to healthcheck this like we do with the pub and priv keys..
  # healthcheck command: openssl dhparam -check < /mnt/dhparam.dh 
  dhparam:
    image: ethorbit/openssl:latest
    volumes:
      - dhparam:/mnt
    command: >
      /bin/sh -c "[[ ! -s /mnt/dhparam.dh ]] 
      && openssl dhparam -out /mnt/dhparam.dh 2048 
      || chown '${cert_u}':'${websites_g}' /mnt/dhparam.dh && exit 0"
    <<: [ *labels ]
    network_mode: none
    restart: on-failure
  
  # Certificate for Development
  mkcert:
    build:
      context: ./build/mkcert
      args:
        - UID=${cert_u}
        - GID=${websites_g}
    profiles:
      - development
    volumes:
      - ${CA_TRUST_STORE_DIR:-/usr/local/share/ca-certificates}:/usr/local/share/ca-certificates
      - mkcert:/mnt
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - PUBLIC_KEY=/mnt/mkcert.pem
      - PRIVATE_KEY=/mnt/mkcert.key
    <<: [ *healthcheck ]
    network_mode: none 
    restart: on-failure
    
  # Certificate for Production w/ renewal
  acme_dns_envsubst:
    build:
      context: ./build/acme_dns_input_output_envsubst
      args:
        FILE_EXTENSION: "cfg"
    profiles:
      - production
    environment:
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - PUBLIC_IP=${PUBLIC_IP}
    volumes:
      - ./data/configs/acme_dns/template:/mnt/input
      - ./data/configs/acme_dns:/mnt/output
    network_mode: none
    <<: [*labels]
    cap_drop:
      - ALL
    cap_add:
      - DAC_OVERRIDE
      - FOWNER
    restart: on-failure
  acme_dns:
    build:
      context: ./build/acme_dns
    profiles:
      - production
    networks:
      - acme_dns
    hostname: acme_dns
    <<: [*labels]
    volumes:
      - ./data/configs/acme_dns:/etc/acme-dns:ro
      - acme_dns_storage:/var/lib/acme-dns
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 127.0.0.1::80/tcp
    depends_on:
      acme_dns_envsubst:
        condition: service_completed_successfully
      acme_dns_rsyslog:
        condition: service_healthy
    logging:
      driver: syslog
      options:
        mode: non-blocking
        syslog-address: "tcp://localhost:${ACME_DNS_RSYSLOG_PORT}"
        tag: "acme_dns"
    healthcheck:
      test: 'curl -f -X GET http://acme_dns/health || exit 1'
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: always
  acme_dns_rsyslog:
    <<: [ *ssl_rsyslog ]
    profiles:
      - production
    build:
      context: ./build/rsyslog
      args:
        - UID=${rsyslog_u}
        - GID=${dns_g}
        - PORT=${ACME_DNS_RSYSLOG_PORT}
    hostname: rsyslog_acme_dns
    ports:
      - 127.0.0.1:${ACME_DNS_RSYSLOG_PORT}:${ACME_DNS_RSYSLOG_PORT}/tcp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/configs/rsyslog/rsyslog.conf:/etc/rsyslog.conf
      - ./data/configs/logrotate/rsyslog.conf:/etc/logrotate.d/rsyslog
      - acme_dns_logs:/logs
      - ${MOUNT_PROC_CPUINFO}:/proc/cpuinfo:rw
      - ${MOUNT_PROC_MEMINFO}:/proc/meminfo:rw
      - ${MOUNT_PROC_SWAPS}:/proc/swaps:rw
      - ${MOUNT_PROC_STAT}:/proc/stat:rw
      - ${MOUNT_PROC_DISKSTATS}:/proc/diskstats:rw
      - ${MOUNT_PROC_UPTIME}:/proc/uptime:rw
      - ${MOUNT_PROC_SLABINFO}:/proc/slabinfo:rw
      - ${MOUNT_SYS_DEVICES_SYSTEM_CPU}:/sys/devices/system/cpu:rw
  certbot_permissions:
    build:
      context: ./build/permissions
    profiles:
      - production
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    command: >
      /bin/sh -c 'chown -fR "${cert_u}":"${websites_g}" /etc/letsencrypt/
      && chown -fR "${cert_u}":"${websites_g}" /var/www/certbot/
      && chmod 750 -R /etc/letsencrypt/'
    cap_drop:
      - ALL
    cap_add:
      - CAP_DAC_OVERRIDE
      - CAP_CHOWN
      - CAP_FOWNER
      - CAP_FSETID
    network_mode: none
    restart: on-failure
  certbot:
    build:
      context: ./build/certbot
      args:
        - UID=${cert_u}
        - GID=${websites_g}
        - ACMEDNS_URL="http://acme_dns"
    profiles:
      - production
    volumes:
      - certbot_conf:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    networks:
      - acme_dns
    <<: [ *healthcheck, *labels ]
    environment:
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - PUBLIC_KEY=/etc/letsencrypt/live/${DOMAIN_NAME}/cert.pem
      - PRIVATE_KEY=/etc/letsencrypt/live/${DOMAIN_NAME}/privkey.pem
    # We need to use the DNS-01 method for wildcard domains. Not optional.
    command: >
      certonly
      ${CERTBOT_TEST_FLAG}
      --non-interactive 
      --manual 
      --agree-tos 
      --keep-until-expiring 
      --email "${ADMIN_EMAIL}" 
      --rsa-key-size 4096 
      --preferred-challenges dns 
      --manual-auth-hook /etc/letsencrypt/acme-dns-auth.py 
      --debug-challenges 
      --verbose 
      -d "${DOMAIN_NAME},*.${DOMAIN_NAME}"
    depends_on:
      certbot_permissions:
        condition: service_completed_successfully
      acme_dns:
        condition: service_healthy
      certbot_rsyslog:
        condition: service_healthy
    logging:
      driver: syslog
      options:
        mode: non-blocking
        syslog-address: "tcp://localhost:${CERTBOT_RSYSLOG_PORT}"
        tag: "certbot"
    restart: always
  certbot_rsyslog:
    <<: [ *ssl_rsyslog ]
    profiles:
      - production
    build:
      context: ./build/rsyslog
      args:
        - UID=${rsyslog_u}
        - GID=${cert_g}
        - PORT=${CERTBOT_RSYSLOG_PORT}
    hostname: rsyslog_certbot
    ports:
      - 127.0.0.1:${CERTBOT_RSYSLOG_PORT}:${CERTBOT_RSYSLOG_PORT}/tcp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/configs/rsyslog/rsyslog.conf:/etc/rsyslog.conf
      - ./data/configs/logrotate/rsyslog.conf:/etc/logrotate.d/rsyslog
      - certbot_logs:/logs
      - ${MOUNT_PROC_CPUINFO}:/proc/cpuinfo:rw
      - ${MOUNT_PROC_MEMINFO}:/proc/meminfo:rw
      - ${MOUNT_PROC_SWAPS}:/proc/swaps:rw
      - ${MOUNT_PROC_STAT}:/proc/stat:rw
      - ${MOUNT_PROC_DISKSTATS}:/proc/diskstats:rw
      - ${MOUNT_PROC_UPTIME}:/proc/uptime:rw
      - ${MOUNT_PROC_SLABINFO}:/proc/slabinfo:rw
      - ${MOUNT_SYS_DEVICES_SYSTEM_CPU}:/sys/devices/system/cpu:rw
volumes:
  dhparam:
  acme_dns_logs:
  acme_dns_storage:
  mkcert:
  certbot_logs:
  certbot_conf:
  certbot_www:
networks:
  acme_dns:
