version: "3.9"
services:
  svencoop:
    build:
      context: ./build/svencoop-server
      args:
        PUID: ${SVENCOOP_UID}
        PGID: ${NZC_GID}
        TZ: ${TZ}
    tty: true 
    stdin_open: true
    environment:
      SRCDS_RUN_ARGS: "-port ${SVENCOOP_PORT:-28015} +maxplayers 12 +map uplink"
    volumes: 
      - ./data/users/passwd:/etc/passwd:ro
      - ./data/users/group:/etc/group:ro
      - ./data/users/shadow:/etc/shadow:ro
      - svencoop:/home/srcds/server
    depends_on:
      users_and_groups:
        condition: service_completed_successfully
      nginx_production: 
        condition: service_healthy
      nginx_development:
        condition: service_healthy
    ports:
      - ${SVENCOOP_PORT:-28015}:${SVENCOOP_PORT}/udp
    networks:
      - svencoop
    cpuset: ${SVENCOOP_CPU}
    cpu_count: 1
    cpu_percent: 10
    cpu_shares: 256
    deploy:
      resources:
        limits:
          memory: 512M 
        reservations:
          memory: 128M  
    blkio_config:
      weight: 150
      device_write_bps:
        - path: ${DISK}
          rate: 10000000
      device_read_bps:
        - path: ${DISK}
          rate: 20000000
      device_read_iops:
        - path: ${DISK}
          rate: 120
      device_write_iops:
        - path: ${DISK}
          rate: 100
    restart: unless-stopped 
volumes:
  svencoop:
networks: 
  svencoop:
    driver: "bridge"
