version: "3.9"
x-svencoop: &svencoop
  build:
    context: ./build/svencoop-server
    args:
      PUID: ${steam_u}
      PGID: ${svencoop_g} 
      UMASK: "007"
  tty: true
  stdin_open: true
  environment:
    START_ARGS: "-port ${SVENCOOP_PORT:-28015} +maxplayers 12 +map uplink"
    RCON_PASSWORD: ${SVENCOOP_PASSWORD}
    STEAM_LOGIN_TOKEN: ${SVENCOOP_LOGIN_TOKEN}
  volumes: 
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./data/configs/users/passwd:/etc/passwd:ro
    - ./data/configs/users/group:/etc/group:ro
    - ./data/configs/users/shadow:/etc/shadow:ro
    - ./data/configs/users/gshadow:/etc/gshadow:ro
    - ${MOUNT_PROC_CPUINFO}:/proc/cpuinfo:rw
    - ${MOUNT_PROC_MEMINFO}:/proc/meminfo:rw
    - ${MOUNT_PROC_SWAPS}:/proc/swaps:rw
    - ${MOUNT_PROC_STAT}:/proc/stat:rw
    - ${MOUNT_PROC_DISKSTATS}:/proc/diskstats:rw
    - ${MOUNT_PROC_UPTIME}:/proc/uptime:rw
    - ${MOUNT_PROC_SLABINFO}:/proc/slabinfo:rw
    - ${MOUNT_SYS_DEVICES_SYSTEM_CPU}:/sys/devices/system/cpu:rw
    - svencoop:${MOUNT_GUEST_STEAMCMD_GAMES}
  ports:
    - ${SVENCOOP_PORT:-28015}:${SVENCOOP_PORT:-28015}/udp
    - ${SVENCOOP_PORT:-28015}:${SVENCOOP_PORT:-28015}/tcp
  networks:
    svencoop:
      ipv4_address: 172.151.1.1
    nginx:
    mysql:
  extra_hosts:
    - "${DOMAIN_NAME}:172.10.1.2"
    - "${WEBSITE_SUBDOMAIN}.${DOMAIN_NAME}:172.10.1.2"
    - "${FASTDL_SUBDOMAIN}.${DOMAIN_NAME}:172.10.1.2"
  hostname: svencoop
  labels:
    - "io.portainer.accesscontrol.teams=svencoop"
  cpuset: ${SVENCOOP_CPU}
  cpu_count: 1
  cpu_shares: 256
  deploy:
    resources:
      limits:
        memory: 512M 
      reservations:
        memory: 128M  
  blkio_config:
    weight: 150
    device_write_bps:
      - path: ${DISK}
        rate: '10m'
    device_read_bps:
      - path: ${DISK}
        rate: '20m'
    device_read_iops:
      - path: ${DISK}
        rate: 120
    device_write_iops:
      - path: ${DISK}
        rate: 100
  logging:
    driver: syslog
    options:
      mode: non-blocking
      syslog-address: "tcp://localhost:${RSYSLOG_PORT}"
      tag: "svencoop"
  restart: always
x-svencoop-depends: &svencoop-depends
  svencoop_permissions:
    condition: service_completed_successfully
  rsyslog:
    condition: service_healthy

services:
  svencoop_permissions:
    build:
      context: ./build/permissions
    volumes:
      - svencoop:/mnt
    command: >
      /bin/sh -c 'chown "${steam_u}":"${svencoop_g}" /mnt 
      && chmod 2770 /mnt 
      && setfacl -d -m u::rwx,g::rwx,o::- /mnt'
    cap_drop:
      - ALL 
    cap_add:
      - CAP_DAC_OVERRIDE
      - CAP_CHOWN
      - CAP_FOWNER
      - CAP_FSETID
    network_mode: none
    restart: on-failure
  svencoop_production:
    profiles:
      - production
    <<: [ *svencoop ]
    depends_on:
      <<: [ *svencoop-depends ]
      nginx_production: 
        condition: service_healthy
  svencoop_development:
    profiles:
      - development
    <<: [ *svencoop ]
    depends_on:
      <<: [ *svencoop-depends ]
      nginx_development:
        condition: service_healthy
volumes:
  svencoop:
networks: 
  svencoop:
    ipam:
      driver: default 
      config:
        - subnet: 172.151.1.0/22
