version: "3.9"

x-synergy-rsyslog: &synergy_rsyslog
  command: '-n'
  tty: true
  stdin_open: true
  healthcheck:
    test: "/healthcheck.sh"
    start_period: 5s
    interval: 5s
    timeout: 10s
    retries: 3
  restart: always

x-synergy: &synergy
  build:
    context: ./build/synergy-server
    args:
      PUID: ${steam_u}
      PGID: ${synergy_g}
      UMASK: "007"
  tty: true
  stdin_open: true
  environment:
    START_ARGS: "-port ${SYNERGY_PORT:-27215} +maxplayers 12 +map d1_trainstation_01"
    PORT: ${SYNERGY_PORT:-27215}
    RCON_PASSWORD: ${SYNERGY_PASSWORD}
    STEAM_LOGIN_TOKEN: ${SYNERGY_LOGIN_TOKEN}
    STEAMCMD_LOGIN_USERNAME: ${STEAMCMD_LOGIN_USERNAME}
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/timezone:/etc/timezone:ro
    - ./data/configs/users/passwd:/etc/passwd:ro
    - ./data/configs/users/group:/etc/group:ro
    - ./data/configs/users/shadow:/etc/shadow:ro
    - ./data/configs/users/gshadow:/etc/gshadow:ro
    - ${MOUNT_PROC_CPUINFO}:/proc/cpuinfo:rw
    - ${MOUNT_PROC_MEMINFO}:/proc/meminfo:rw
    - ${MOUNT_PROC_SWAPS}:/proc/swaps:rw
    - ${MOUNT_PROC_STAT}:/proc/stat:rw
    - ${MOUNT_PROC_DISKSTATS}:/proc/diskstats:rw
    - ${MOUNT_PROC_UPTIME}:/proc/uptime:rw
    - ${MOUNT_PROC_SLABINFO}:/proc/slabinfo:rw
    - ${MOUNT_SYS_DEVICES_SYSTEM_CPU}:/sys/devices/system/cpu:rw
    - synergy:${MOUNT_GUEST_STEAMCMD_GAMES}
  ports:
    - ${SYNERGY_PORT:-27215}:${SYNERGY_PORT:-27215}/udp
    - ${SYNERGY_PORT:-27215}:${SYNERGY_PORT:-27215}/tcp
  networks:
    synergy:
      ipv4_address: 172.152.1.1
    nginx:
    mysql:
  extra_hosts:
    - "${DOMAIN_NAME}:172.10.1.2"
    - "${WEBSITE_SUBDOMAIN}.${DOMAIN_NAME}:172.10.1.2"
    - "${FASTDL_SUBDOMAIN}.${DOMAIN_NAME}:172.10.1.2"
  hostname: synergy
  labels:
    - "io.portainer.accesscontrol.teams=synergy"
  cpuset: ${SYNERGY_CPU}
  cpu_count: 1
  cpu_shares: 256
  deploy:
    resources:
      limits:
        memory: 512M 
      reservations:
        memory: 128M  
  blkio_config:
    weight: 150
    device_write_bps:
      - path: ${DISK}
        rate: '60m'
    device_read_bps:
      - path: ${DISK}
        rate: '60m'
    device_read_iops:
      - path: ${DISK}
        rate: 1000
    device_write_iops:
      - path: ${DISK}
        rate: 1000
  logging:
    driver: syslog
    options:
      mode: non-blocking
      syslog-address: "tcp://localhost:${SYNERGY_RSYSLOG_PORT}"
      tag: "synergy"
  restart: always
x-synergy-depends: &synergy-depends
  synergy_permissions:
    condition: service_completed_successfully
  synergy_rsyslog:
    condition: service_healthy

services:
  synergy_permissions:
    build:
      context: ./build/permissions
    volumes:
      - synergy:/mnt
    command: >
      /bin/sh -c 'chown "${steam_u}":"${synergy_g}" /mnt 
      && chmod 2770 /mnt 
      && setfacl -d -m u::rwx,g::rwx,o::- /mnt'
    cap_drop:
      - ALL 
    cap_add:
      - CAP_DAC_OVERRIDE
      - CAP_CHOWN
      - CAP_FOWNER
      - CAP_FSETID
    network_mode: none
    restart: on-failure
  synergy_production:
    profiles:
      - production
    <<: [ *synergy ]
    depends_on:
      <<: [ *synergy-depends ]
      nginx_production: 
        condition: service_healthy
  synergy_development:
    profiles:
      - development
    <<: [ *synergy ]
    depends_on:
      <<: [ *synergy-depends ]
      nginx_development:
        condition: service_healthy

  synergy_rsyslog:
    <<: [ *synergy_rsyslog ]
    build:
      context: ./build/rsyslog
      args:
        - UID=${rsyslog_u}
        - GID=${synergy_g}
        - PORT=${SYNERGY_RSYSLOG_PORT}
    hostname: synergy_rsyslog
    ports:
      - 127.0.0.1:${SYNERGY_RSYSLOG_PORT}:${SYNERGY_RSYSLOG_PORT}/tcp
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/configs/rsyslog/rsyslog.conf:/etc/rsyslog.conf
      - synergy_logs:/logs
volumes:
  synergy_logs:
  synergy:
networks: 
  synergy:
    ipam:
      driver: default 
      config:
        - subnet: 172.152.1.0/22
