version: '3.9'
services:
  tc:
    image: ethorbit/docker-tc:latest
    cap_add:
      - NET_ADMIN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/docker-tc:/var/docker-tc
    environment:
      HTTP_BIND: 127.0.0.1
      HTTP_PORT: "${TC_HTTP_PORT:-4080}"
    network_mode: host
    restart: always
