version: "3.9"
services:
  test:
    image: alpine:latest
    volumes:
      - ./data/users/passwd:/etc/passwd:ro
      - ./data/users/group:/etc/group:ro
      - ./data/users/shadow:/etc/shadow:ro
      - pam:/etc/pam.d
    command: /bin/sh -c "while true; do sleep 1; done"
    user: "${NGINX_UID}"
    network_mode: none

