version: "3.9"
services:
  watchtower:
    image: containrrr/watchtower:1.5.3
    profiles:
      - update
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_RUN_ONCE=1

