version: "3.9"

services:
  users_and_groups:
    image: ethorbit/user-manager:latest
    env_file:
      - ../.users.env
    environment:
      - HUID=${HUID}
      - HGID=${HGID}
    profiles:
      - setup_users
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/configs/users:/mnt
      #- ./data/configs/users/skel:/etc/skel
      - home:/home
      #- pam:/etc/pam.d
    network_mode: none
volumes:
  home:
    #  pam:

